/*
 * BSD 2-Clause License
 *
 * Copyright (c) 2021, Riley McGee
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package com.wastedbankspace.model.locations;

import com.wastedbankspace.model.StorableItem;
import lombok.Getter;
import net.runelite.api.ItemComposition;
import net.runelite.api.gameval.ItemID;

@Getter
public enum ArmourCase implements StorableItem
{
    // Adventurer's outfit (tier 1)
    ADVENTURERS_HOOD_T1(ItemID.ADVENTURERS_HOOD_T1),
    ADVENTURERS_TOP_T1(ItemID.ADVENTURERS_TOP_T1),
    ADVENTURERS_TROUSERS_T1(ItemID.ADVENTURERS_LEGS_T1),
    ADVENTURERS_BOOTS_T1(ItemID.ADVENTURERS_BOOTS_T1),
    // Adventurer's outfit (tier 2)
    ADVENTURERS_HOOD_T2(ItemID.ADVENTURERS_HOOD_T2),
    ADVENTURERS_TOP_T2(ItemID.ADVENTURERS_TOP_T2),
    ADVENTURERS_TROUSERS_T2(ItemID.ADVENTURERS_LEGS_T2),
    ADVENTURERS_BOOTS_T2(ItemID.ADVENTURERS_BOOTS_T2),
    // Adventurer's outfit (tier 3)
    ADVENTURERS_HOOD_T3(ItemID.ADVENTURERS_HOOD_T3),
    ADVENTURERS_TOP_T3(ItemID.ADVENTURERS_TOP_T3),
    ADVENTURERS_TROUSERS_T3(ItemID.ADVENTURERS_LEGS_T3),
    ADVENTURERS_BOOTS_T3(ItemID.ADVENTURERS_BOOTS_T3),
    // Aux Adventurer's outfit
    ADVENTURERS_VAMBRACERS(ItemID.ADVENTURERS_VAMBRACES),
    ADVENTURERS_CAPE(ItemID.ADVENTURERS_CAPE),
    // Alchemist's outfit
    PRESCRIPTION_GOGGLES(ItemID.MM_ALCHEMIST_HAT, true),
    PRESCRIPTION_GOGGLES_29976(ItemID.MM_ALCHEMIST_HAT_ALT, true),
    ALCHEMIST_LABCOAT(ItemID.MM_ALCHEMIST_BODY),
    ALCHEMIST_LABCOAT_29980(ItemID.MM_ALCHEMIST_BODY_ALT),
    ALCHEMIST_PANTS(ItemID.MM_ALCHEMIST_LEGS),
    ALCHEMIST_PANTS_29984(ItemID.MM_ALCHEMIST_LEGS_ALT),
    ALCHEMIST_GLOVES(ItemID.MM_ALCHEMIST_GLOVES),
    // Angler outfit is storable in the tackle box
    // Spirit angler outfit is storable in the tackle box
    ARDOUGNE_KNIGHT_HELM(ItemID.ARDOUGNE_KNIGHT_HELM),
    ARDOUGNE_KNIGHT_PLATEBODY(ItemID.ARDOUGNE_KNIGHT_BODY),
    ARDOUGNE_KNIGHT_PLATELEGS(ItemID.ARDOUGNE_KNIGHT_LEGS),
    // Bomber jacket costume
    BOMBER_CAP(ItemID.ZEP_BOMBER_CAP),
    CAP_AND_GOGGLES(ItemID.ZEP_BOMBER_CAP_GOGGLES),
    BOMBER_JACKET(ItemID.ZEP_BOMBER_JACKET),
    // Builder's costume
    HARD_HAT(ItemID.TOL_PLAYER_CONSTRUCTION_HARDHAT),
    BUILDERS_SHIRT(ItemID.TOL_PLAYER_CONSTRUCTION_SHIRT),
    BUILDERS_TROUSERS(ItemID.TOL_PLAYER_CONSTRUCTION_TROUSERS),
    BUILDERS_BOOTS(ItemID.TOL_PLAYER_CONSTRUCTION_BOOTS),
    // Butler's uniform
    BUTLERS_UNIFORM(ItemID.DOTI_BUTLERUNIFORM_VILLA),
    BUTLERS_UNIFORM_29915(ItemID.DOTI_BUTLERUNIFORM_LEGS_VILLA),
    BUTLERS_UNIFORM_29916(ItemID.DOTI_BUTLERUNIFORM),
    BUTLERS_UNIFORM_29918(ItemID.DOTI_BUTLERUNIFORM_LEGS),
    // Desert camo outfit
    DESERT_CAMO_TOP(ItemID.HUNTING_CAMOFLAUGE_ROBE_DESERT),
    DESERT_CAMO_LEGS(ItemID.HUNTING_TROUSERS_DESERT),
    // Jungle camo outfit
    JUNGLE_CAMO_TOP(ItemID.HUNTING_CAMOFLAUGE_ROBE_JUNGLE),
    JUNGLE_CAMO_LEGS(ItemID.HUNTING_TROUSERS_JUNGLE),
    // Polar camo outfit
    POLAR_CAMO_TOP(ItemID.HUNTING_CAMOFLAUGE_ROBE_POLAR),
    POLAR_CAMO_LEGS(ItemID.HUNTING_TROUSERS_POLAR),
    // Woodland camo outfit
    WOOD_CAMO_TOP(ItemID.HUNTING_CAMOFLAUGE_ROBE_WOOD),
    WOOD_CAMO_LEGS(ItemID.HUNTING_TROUSERS_WOOD),
    // Leagues Canes
    RAGING_ECHOES_CANE(ItemID.LEAGUE5_RELIC_HUNTER_CANE),
    SHATTERED_CANE(ItemID.LEAGUE_3_CANE),
    TRAILBLAZER_CANE(ItemID.TRAILBLAZER_CANE),
    TWISTED_CANE(ItemID.TWISTED_CANE),
    // Castle Wars armour (1)
    DECORATIVE_HELM(ItemID.CASTLEWARS_MED_HELM),
    DECORATIVE_FULL_HELM(ItemID.CASTLEWARS_FULL_HELM),
    DECORATIVE_ARMOUR(ItemID.CASTLEWARS_ARMOUR_BODY),
    DECORATIVE_ARMOUR_4070(ItemID.CASTLEWARS_ARMOUR_LEGS),
    DECORATIVE_ARMOUR_11893(ItemID.CASTLEWARS_ARMOUR_SKIRT),
    DECORATIVE_SHIELD(ItemID.CASTLEWARS_SHIELD),
    DECORATIVE_BOOTS(ItemID.CASTLEWARS_BOOTS),
    // Castle Wars armour (2)
    DECORATIVE_HELM_4506(ItemID.CASTLEWARS_MED_HELM_2),
    DECORATIVE_FULL_HELM_25169(ItemID.CASTLEWARS_FULL_HELM_2),
    DECORATIVE_ARMOUR_4504(ItemID.CASTLEWARS_ARMOUR_BODY_2),
    DECORATIVE_ARMOUR_4505(ItemID.CASTLEWARS_ARMOUR_LEGS_2),
    DECORATIVE_ARMOUR_11894(ItemID.CASTLEWARS_ARMOUR_SKIRT_2),
    DECORATIVE_SHIELD_4507(ItemID.CASTLEWARS_SHIELD_2),
    DECORATIVE_BOOTS_25167(ItemID.CASTLEWARS_BOOTS_2),
    // Castle Wars armour (3)
    DECORATIVE_HELM_4511(ItemID.CASTLEWARS_MED_HELM_3),
    DECORATIVE_FULL_HELM_25174(ItemID.CASTLEWARS_FULL_HELM_3),
    DECORATIVE_ARMOUR_4509(ItemID.CASTLEWARS_ARMOUR_BODY_3),
    DECORATIVE_ARMOUR_4510(ItemID.CASTLEWARS_ARMOUR_LEGS_3),
    DECORATIVE_ARMOUR_11895(ItemID.CASTLEWARS_ARMOUR_SKIRT_3),
    DECORATIVE_SHIELD_4512(ItemID.CASTLEWARS_SHIELD_3),
    DECORATIVE_BOOTS_25171(ItemID.CASTLEWARS_BOOTS_3),
    // Castle Wars sword (1)
    DECORATIVE_SWORD(ItemID.CASTLEWARS_SWORD),
    // Castle Wars sword (2)
    DECORATIVE_SWORD_4503(ItemID.CASTLEWARS_SWORD_2),
    // Castle Wars sword (3)
    DECORATIVE_SWORD_4508(ItemID.CASTLEWARS_SWORD_3),
    // Castle Wars mage armour
    DECORATIVE_ARMOUR_11896(ItemID.CASTLEWARS_MAGE_TOP),
    DECORATIVE_ARMOUR_MAGIC_LEGS(ItemID.CASTLEWARS_MAGE_LEGS),
    DECORATIVE_ARMOUR_11898(ItemID.CASTLEWARS_MAGE_HAT),
    // Castle Wars ranger armour
    DECORATIVE_ARMOUR_11899(ItemID.CASTLEWARS_RANGE_TOP),
    DECORATIVE_ARMOUR_11900(ItemID.CASTLEWARS_RANGE_LEGS),
    DECORATIVE_ARMOUR_11901(ItemID.CASTLEWARS_RANGE_QUIVER),
    //Chompy Bird Hunting Hats
    CHOMPY_BIRD_HAT(ItemID.CBHAT1),
    CHOMPY_BIRD_HAT_2979(ItemID.CBHAT2),
    CHOMPY_BIRD_HAT_2980(ItemID.CBHAT3),
    CHOMPY_BIRD_HAT_2981(ItemID.CBHAT4),
    CHOMPY_BIRD_HAT_2982(ItemID.CBHAT5),
    CHOMPY_BIRD_HAT_2983(ItemID.CBHAT6),
    CHOMPY_BIRD_HAT_2984(ItemID.CBHAT7),
    CHOMPY_BIRD_HAT_2985(ItemID.CBHAT8),
    CHOMPY_BIRD_HAT_2986(ItemID.CBHAT9),
    CHOMPY_BIRD_HAT_2987(ItemID.CBHAT10),
    CHOMPY_BIRD_HAT_2988(ItemID.CBHAT11),
    CHOMPY_BIRD_HAT_2989(ItemID.CBHAT12),
    CHOMPY_BIRD_HAT_2990(ItemID.CBHAT13),
    CHOMPY_BIRD_HAT_2991(ItemID.CBHAT14),
    CHOMPY_BIRD_HAT_2992(ItemID.CBHAT15),
    CHOMPY_BIRD_HAT_2993(ItemID.CBHAT16),
    CHOMPY_BIRD_HAT_2994(ItemID.CBHAT17),
    CHOMPY_BIRD_HAT_2995(ItemID.CBHAT18),
    // Clue hunter outfit
    CLUE_HUNTER_GARB(ItemID.CLUE_HUNTER_GARB),
    CLUE_HUNTER_TROUSERS(ItemID.CLUE_HUNTER_TROUSERS),
    CLUE_HUNTER_GLOVES(ItemID.CLUE_HUNTER_GLOVES),
    CLUE_HUNTER_BOOTS(ItemID.CLUE_HUNTER_BOOTS),
    CLUE_HUNTER_CLOAK(ItemID.CLUE_HUNTER_CLOAK),
    // Corrupted armour
    CORRUPTED_HELM(ItemID.RAIDS_CLUEFEST_HELM),
    CORRUPTED_PLATEBODY(ItemID.RAIDS_CLUEFEST_PLATEBODY),
    CORRUPTED_PLATELEGS(ItemID.RAIDS_CLUEFEST_PLATELEGS),
    CORRUPTED_PLATESKIRT(ItemID.RAIDS_CLUEFEST_PLATESKIRT),
    CORRUPTED_KITESHIELD(ItemID.RAIDS_CLUEFEST_KITESHIELD),
    // Deadman armour
    DEADMANS_CHEST(ItemID.DEADMAN_BODY),
    DEADMANS_LEGS(ItemID.DEADMAN_LEGS),
    DEADMANS_CAPE(ItemID.DEADMAN_CAPE),
    // Dragonstone armour
    DRAGONSTONE_FULL_HELM(ItemID.DRAGONSTONE_HELMET),
    DRAGONSTONE_PLATEBODY(ItemID.DRAGONSTONE_PLATEBODY),
    DRAGONSTONE_PLATELEGS(ItemID.DRAGONSTONE_PLATELEGS),
    DRAGONSTONE_BOOTS(ItemID.DRAGONSTONE_ARMOURED_BOOTS),
    DRAGONSTONE_GAUNTLETS(ItemID.DRAGONSTONE_GAUNTLETS),
    // Elite black armour
    ELITE_BLACK_FULL_HELM(ItemID.ELITE_BLACK_FULL_HELM),
    ELITE_BLACK_PLATEBODY(ItemID.ELITE_BLACK_PLATEBODY),
    ELITE_BLACK_PLATELEGS(ItemID.ELITE_BLACK_PLATELEGS),
    // Farmer's outfit
    FARMERS_STRAWHAT(ItemID.TITHE_REWARD_HAT_MALE),
    FARMERS_STRAWHAT_13647(ItemID.TITHE_REWARD_HAT_FEMALE),
    FARMERS_JACKET(ItemID.TITHE_REWARD_TORSO_MALE),
    FARMERS_SHIRT(ItemID.TITHE_REWARD_TORSO_FEMALE),
    FARMERS_BORO_TROUSERS(ItemID.TITHE_REWARD_LEGS_MALE),
    FARMERS_BORO_TROUSERS_13641(ItemID.TITHE_REWARD_LEGS_FEMALE),
    FARMERS_BOOTS(ItemID.TITHE_REWARD_FEET_MALE),
    FARMERS_BOOTS_13645(ItemID.TITHE_REWARD_FEET_FEMALE),
    // Crazy Archaeologist's Fedora
    FEDORA(ItemID.FEDORA),
    // Speed running stopwatch
    GIANT_STOPWATCH(ItemID.GIANT_STOPWATCH),
    // Ham outfit
    HAM_HOOD(ItemID.HAM_HOOD),
    HAM_SHIRT(ItemID.HAM_SHIRT),
    HAM_ROBE(ItemID.HAM_ROBE),
    HAM_GLOVES(ItemID.HAM_GLOVES),
    HAM_BOOTS(ItemID.HAM_BOOTS),
    HAM_CLOAK(ItemID.HAM_CLOAK),
    HAM_LOGO(ItemID.HAM_BADGE),
    // Halos
    ANCIENT_HALO(ItemID.ZAROS_HALO),
    ARMADYL_HALO(ItemID.ARMADYL_HALO),
    BANDOS_HALO(ItemID.BANDOS_HALO),
    BRASSICA_HALO(ItemID.BRASSICA_HALO),
    GUTHIX_HALO(ItemID.CASTLEWARS_GUTHIX_HALO),
    SARADOMIN_HALO(ItemID.CASTLEWARS_SARADOMIN_HALO),
    SEREN_HALO(ItemID.SEREN_HALO),
    ZAMORAK_HALO(ItemID.CASTLEWARS_ZAMORAK_HALO),
    // Clue hunter helmet
    HELM_OF_RAEDWALD(ItemID.RAEDWALD_HELM),
    // Hunter outfits
    GRAAHK_HEADDRESS(ItemID.HUNTING_HAT_LEOPARD),
    GRAAHK_TOP(ItemID.HUNTING_TORSO_LEOPARD),
    GRAAHK_LEGS(ItemID.HUNTING_TROUSERS_LEOPARD),
    KYATT_HAT(ItemID.HUNTING_HAT_TIGER),
    KYATT_TOP(ItemID.HUNTING_TORSO_TIGER),
    KYATT_LEGS(ItemID.HUNTING_TROUSERS_TIGER),
    LARUPIA_HAT(ItemID.HUNTING_HAT_JAGUAR),
    LARUPIA_TOP(ItemID.HUNTING_TORSO_JAGUAR),
    LARUPIA_LEGS(ItemID.HUNTING_TROUSERS_JAGUAR),
    // Guild Hunter outfit is storable in the hunter kit
    // Inquisitor's armour
    INQUISITORS_GREAT_HELM(ItemID.INQUISITORS_HELM, true),
    INQUISITORS_HAUBERK(ItemID.INQUISITORS_BODY, true),
    INQUISITORS_PLATESKIRT(ItemID.INQUISITORS_SKIRT, true),
    // Justiciar armour
    JUSTICIAR_FACEGUARD(ItemID.JUSTICIAR_FACEGUARD, true),
    JUSTICIAR_CHESTGUARD(ItemID.JUSTICIAR_CHESTGUARD, true),
    JUSTICIAR_LEGGUARDS(ItemID.JUSTICIAR_LEG_GUARDS, true),
    // Lumberjack outfit - can be stored in FORESTRY_KIT, FORESTRY_BASKET, or OPEN_FORESTRY_BASKET, if CLOTHES_POUCH is installed on any of them
    LUMBERJACK_HAT_AC(ItemID.RAMBLE_LUMBERJACK_HAT),
    LUMBERJACK_TOP_AC(ItemID.RAMBLE_LUMBERJACK_TOP),
    LUMBERJACK_LEGS_AC(ItemID.RAMBLE_LUMBERJACK_LEGS),
    LUMBERJACK_BOOTS_AC(ItemID.RAMBLE_LUMBERJACK_BOOTS),
    // Forestry Outfit
    FORESTRY_HAT_AC(ItemID.FORESTRY_LUMBERJACK_HAT),
    FORESTRY_TOP_AC(ItemID.FORESTRY_LUMBERJACK_TOP),
    FORESTRY_LEGS_AC(ItemID.FORESTRY_LUMBERJACK_LEGS),
    FORESTRY_BOOTS_AC(ItemID.FORESTRY_LUMBERJACK_BOOTS),
    // Masori armour
    MASORI_MASK(ItemID.MASORI_MASK, true),
    MASORI_BODY(ItemID.MASORI_BODY, true),
    MASORI_CHAPS(ItemID.MASORI_CHAPS, true),
    // Masori armour (fortified)
    MASORI_MASK_F(ItemID.MASORI_MASK_FORTIFIED, true),
    MASORI_BODY_F(ItemID.MASORI_BODY_FORTIFIED, true),
    MASORI_CHAPS_F(ItemID.MASORI_CHAPS_FORTIFIED, true),
    // Mining gloves
    MINING_GLOVES(ItemID.MGUILD_GLOVES),
    SUPERIOR_MINING_GLOVES(ItemID.MGUILD_GLOVES_SUPERIOR),
    EXPERT_MINING_GLOVES(ItemID.MGUILD_GLOVES_EXPERT),
    // Mixed hide armour
    MIXED_HIDE_TOP(ItemID.HIDE_TOP),
    MIXED_HIDE_LEGS(ItemID.HIDE_LEGS),
    MIXED_HIDE_BOOTS(ItemID.HIDE_BOOTS),
    MIXED_HIDE_CAPE(ItemID.HIDE_CAPE),
    // Mourner gear
    GAS_MASK(ItemID.GASMASK),
    MOURNER_TOP(ItemID.MOURNING_MOURNER_TOP),
    MOURNER_TROUSERS(ItemID.MOURNING_MOURNER_LEGS),
    MOURNER_BOOTS(ItemID.MOURNING_MOURNER_BOOTS),
    MOURNER_GLOVES(ItemID.MOURNING_MOURNER_GLOVES),
    MOURNER_CLOAK(ItemID.MOURNING_MOURNER_CLOAK),
    // Oathplate armour
    OATHPLATE_HELM(ItemID.OATHPLATE_HELM, true),
    OATHPLATE_CHEST(ItemID.OATHPLATE_CHEST, true),
    OATHPLATE_LEGS(ItemID.OATHPLATE_LEGS, true),
    // Obsidian armour
    OBSIDIAN_HELMET(ItemID.OBSIDIAN_HELMET, true),
    OBSIDIAN_PLATEBODY(ItemID.OBSIDIAN_PLATEBODY, true),
    OBSIDIAN_PLATELEGS(ItemID.OBSIDIAN_PLATELEGS, true),
    // Ornate armour
    ORNATE_HELM(ItemID.ORNATE_HELM),
    ORNATE_TOP(ItemID.ORNATE_TOP),
    ORNATE_LEGS(ItemID.ORNATE_LEGS),
    ORNATE_GLOVES(ItemID.ORNATE_GLOVES),
    ORNATE_BOOTS(ItemID.ORNATE_BOOTS),
    ORNATE_CAPE(ItemID.ORNATE_CAPE),
    // Barbarian Assault armour
    FIGHTER_HAT(ItemID.BARBASSAULT_PENANCE_FIGHTER_HAT),
    FIGHTER_TORSO(ItemID.BARBASSAULT_PENANCE_FIGHTER_TORSO),
    PENANCE_GLOVES(ItemID.BARBASSAULT_PENANCE_GLOVES),
    HEALER_HAT(ItemID.BARBASSAULT_PENANCE_HEALER_HAT),
    RANGER_HAT(ItemID.BARBASSAULT_PENANCE_RANGER_HAT),
    RUNNER_BOOTS(ItemID.BARBASSAULT_PENANCE_RUNNER_BOOTS),
    RUNNER_HAT(ItemID.BARBASSAULT_PENANCE_RUNNER_HAT),
    PENANCE_SKIRT(ItemID.BARBASSAULT_PENANCE_RANGER_LEGS),
    // Prospector outfit
    PROSPECTOR_HELMET(ItemID.MOTHERLODE_REWARD_HAT),
    PROSPECTOR_JACKET(ItemID.MOTHERLODE_REWARD_TOP),
    PROSPECTOR_LEGS(ItemID.MOTHERLODE_REWARD_LEGS),
    PROSPECTOR_BOOTS(ItemID.MOTHERLODE_REWARD_BOOTS),
    GOLDEN_PROSPECTOR_HELMET(ItemID.MOTHERLODE_REWARD_HAT_GOLD),
    GOLDEN_PROSPECTOR_JACKET(ItemID.MOTHERLODE_REWARD_TOP_GOLD),
    GOLDEN_PROSPECTOR_LEGS(ItemID.MOTHERLODE_REWARD_LEGS_GOLD),
    GOLDEN_PROSPECTOR_BOOTS(ItemID.MOTHERLODE_REWARD_BOOTS_GOLD),
    // Radiant oathplate armour
    RADIANT_OATHPLATE_HELM(ItemID.RADIANT_OATHPLATE_HELM),
    RADIANT_OATHPLATE_CHEST(ItemID.RADIANT_OATHPLATE_CHEST),
    RADIANT_OATHPLATE_LEGS(ItemID.RADIANT_OATHPLATE_LEGS),
    // Raging Echoes Relic Hunter (T1)
    RAGING_ECHOES_HAT_T1(ItemID.LEAGUE5_RELIC_HUNTER_HAT_T1),
	RAGING_ECHOES_TOP_T1(ItemID.LEAGUE5_RELIC_HUNTER_TOP_T1),
	RAGING_ECHOES_ROBESKIRT_T1(ItemID.LEAGUE5_RELIC_HUNTER_LEGS_T1),
	RAGING_ECHOES_BOOTS_T1(ItemID.LEAGUE5_RELIC_HUNTER_BOOTS_T1),
    // Raging Echoes Relic Hunter (T2)
	RAGING_ECHOES_HAT_T2(ItemID.LEAGUE5_RELIC_HUNTER_HAT_T2),
	RAGING_ECHOES_TOP_T2(ItemID.LEAGUE5_RELIC_HUNTER_TOP_T2),
	RAGING_ECHOES_ROBESKIRT_T2(ItemID.LEAGUE5_RELIC_HUNTER_LEGS_T2),
	RAGING_ECHOES_BOOTS_T2(ItemID.LEAGUE5_RELIC_HUNTER_BOOTS_T2),
    // Raging Echoes Relic Hunter (T3)
	RAGING_ECHOES_HAT_T3(ItemID.LEAGUE5_RELIC_HUNTER_HAT_T3),
	RAGING_ECHOES_TOP_T3(ItemID.LEAGUE5_RELIC_HUNTER_TOP_T3),
	RAGING_ECHOES_ROBESKIRT_T3(ItemID.LEAGUE5_RELIC_HUNTER_LEGS_T3),
	RAGING_ECHOES_BOOTS_T3(ItemID.LEAGUE5_RELIC_HUNTER_BOOTS_T3),
    // Rockshell armour
    ROCKSHELL_HELM(ItemID.DAGGANOTH_MELEE_HELM),
    ROCKSHELL_PLATE(ItemID.DAGGANOTH_MELEE_BODY),
    ROCKSHELL_LEGS(ItemID.DAGGANOTH_MELEE_LEGS),
    ROCKSHELL_GLOVES(ItemID.DAGGANOTH_MELEE_GLOVES),
    ROCKSHELL_BOOTS(ItemID.DAGGANOTH_MELEE_FEET),
    // Rogue equipment
    ROGUE_MASK(ItemID.ROGUESDEN_HELM),
    ROGUE_TOP(ItemID.ROGUESDEN_BODY),
    ROGUE_GLOVES(ItemID.ROGUESDEN_GLOVES),
    ROGUE_TROUSERS(ItemID.ROGUESDEN_LEGS),
    ROGUE_BOOTS(ItemID.ROGUESDEN_BOOTS),
    // Shattered Relic Hunter (T1)
    SHATTERED_HOOD_T1(ItemID.LEAGUE_3_RELIC_HUNTER_HOOD_T1),
    SHATTERED_TOP_T1(ItemID.LEAGUE_3_RELIC_HUNTER_TOP_T1),
    SHATTERED_TROUSERS_T1(ItemID.LEAGUE_3_RELIC_HUNTER_LEGS_T1),
    SHATTERED_BOOTS_T1(ItemID.LEAGUE_3_RELIC_HUNTER_BOOTS_T1),
    // Shattered Relic Hunter (T2)
    SHATTERED_HOOD_T2(ItemID.LEAGUE_3_RELIC_HUNTER_HOOD_T2),
    SHATTERED_TOP_T2(ItemID.LEAGUE_3_RELIC_HUNTER_TOP_T2),
    SHATTERED_TROUSERS_T2(ItemID.LEAGUE_3_RELIC_HUNTER_LEGS_T2),
    SHATTERED_BOOTS_T2(ItemID.LEAGUE_3_RELIC_HUNTER_BOOTS_T2),
    // Shattered Relic Hunter (T3)
    SHATTERED_HOOD_T3(ItemID.LEAGUE_3_RELIC_HUNTER_HOOD_T3),
    SHATTERED_TOP_T3(ItemID.LEAGUE_3_RELIC_HUNTER_TOP_T3),
    SHATTERED_TROUSERS_T3(ItemID.LEAGUE_3_RELIC_HUNTER_LEGS_T3),
    SHATTERED_BOOTS_T3(ItemID.LEAGUE_3_RELIC_HUNTER_BOOTS_T3),
    // Shayzien armour (tier 1)
    SHAYZIEN_HELM_1(ItemID.SHAYZIEN_HELM_1),
    SHAYZIEN_PLATEBODY_1(ItemID.SHAYZIEN_BODY_1),
    SHAYZIEN_GREAVES_1(ItemID.SHAYZIEN_LEGS_1),
    SHAYZIEN_GLOVES_1(ItemID.SHAYZIEN_GLOVES_1),
    SHAYZIEN_BOOTS_1(ItemID.SHAYZIEN_BOOTS_1),
    // Shayzien armour (tier 2)
    SHAYZIEN_HELM_2(ItemID.SHAYZIEN_HELM_2),
    SHAYZIEN_PLATEBODY_2(ItemID.SHAYZIEN_BODY_2),
    SHAYZIEN_GREAVES_2(ItemID.SHAYZIEN_LEGS_2),
    SHAYZIEN_GLOVES_2(ItemID.SHAYZIEN_GLOVES_2),
    SHAYZIEN_BOOTS_2(ItemID.SHAYZIEN_BOOTS_2),
    // Shayzien armour (tier 3)
    SHAYZIEN_HELM_3(ItemID.SHAYZIEN_HELM_3),
    SHAYZIEN_PLATEBODY_3(ItemID.SHAYZIEN_BODY_3),
    SHAYZIEN_GREAVES_3(ItemID.SHAYZIEN_LEGS_3),
    SHAYZIEN_GLOVES_3(ItemID.SHAYZIEN_GLOVES_3),
    SHAYZIEN_BOOTS_3(ItemID.SHAYZIEN_BOOTS_3),
    // Shayzien armour (tier 4)
    SHAYZIEN_HELM_4(ItemID.SHAYZIEN_HELM_4),
    SHAYZIEN_PLATEBODY_4(ItemID.SHAYZIEN_BODY_4),
    SHAYZIEN_GREAVES_4(ItemID.SHAYZIEN_LEGS_4),
    SHAYZIEN_GLOVES_4(ItemID.SHAYZIEN_GLOVES_4),
    SHAYZIEN_BOOTS_4(ItemID.SHAYZIEN_BOOTS_4),
    // Shayzien armour (tier 5)
    SHAYZIEN_HELM_5(ItemID.SHAYZIEN_HELM_5),
    SHAYZIEN_PLATEBODY_5(ItemID.SHAYZIEN_BODY_5),
    SHAYZIEN_GREAVES_5(ItemID.SHAYZIEN_LEGS_5),
    SHAYZIEN_GLOVES_5(ItemID.SHAYZIEN_GLOVES_5),
    SHAYZIEN_BOOTS_5(ItemID.SHAYZIEN_BOOTS_5),
    // Snakeskin armour
    SNAKESKIN_BANDANA(ItemID.SNAKESKIN_BANDANA),
    SNAKESKIN_BODY(ItemID.SNAKESKIN_BODY),
    SNAKESKIN_BOOTS(ItemID.SNAKESKIN_BOOTS),
    SNAKESKIN_CHAPS(ItemID.SNAKESKIN_CHAPS),
    SNAKESKIN_VAMBRACES(ItemID.SNAKESKIN_VAMBRACES),
    // Spined armour
    SPINED_HELM(ItemID.DAGGANOTH_RANGED_HELM),
    SPINED_BODY(ItemID.DAGGANOTH_RANGED_BODY),
    SPINED_CHAPS(ItemID.DAGGANOTH_RANGED_LEGS),
    SPINED_GLOVES(ItemID.DAGGANOTH_RANGE_GLOVES),
    SPINED_BOOTS(ItemID.DAGGANOTH_RANGE_FEET),
    // Stronghold of Security Boots
    FANCY_BOOTS(ItemID.SOS_BOOTS),
    FIGHTING_BOOTS(ItemID.SOS_BOOTS2),
    FANCIER_BOOTS(ItemID.SOS_BOOTS3),
    // Sunfire fanatic armour
    SUNFIRE_FANATIC_HELM(ItemID.SUNFIRE_HELM, true),
    SUNFIRE_FANATIC_CUIRASS(ItemID.SUNFIRE_BODY, true),
    SUNFIRE_FANATIC_CHAUSSES(ItemID.SUNFIRE_LEGS, true),
    // Swift blade
    SWIFT_BLADE(ItemID.SWIFT_BLADE, true),
    // Initiate armour
    INITIATE_SALLET(ItemID.BASIC_TK_HELM),
    INITIATE_HAUBERK(ItemID.BASIC_TK_BODY),
    INITIATE_CUISSE(ItemID.BASIC_TK_LEGS),
    // Proselyte armour
    PROSELYTE_SALLET(ItemID.BASIC_TK_RANK2_HELM),
    PROSELYTE_TASSET(ItemID.BASIC_TK_RANK2_PLATESKIRT),
    PROSELYTE_HAUBERK(ItemID.BASIC_TK_RANK2_BODY),
    PROSELYTE_CUISSE(ItemID.BASIC_TK_RANK2_LEGS),
    // Trailblazer Relic Hunter (T1)
    TRAILBLAZER_HOOD_T1(ItemID.TRAILBLAZER_RELIC_HUNTER_HOOD_T1),
    TRAILBLAZER_TOP_T1(ItemID.TRAILBLAZER_RELIC_HUNTER_TOP_T1),
    TRAILBLAZER_TROUSERS_T1(ItemID.TRAILBLAZER_RELIC_HUNTER_LEGS_T1),
    TRAILBLAZER_BOOTS_T1(ItemID.TRAILBLAZER_RELIC_HUNTER_BOOTS_T1),
    // Trailblazer Relic Hunter (T2)
    TRAILBLAZER_HOOD_T2(ItemID.TRAILBLAZER_RELIC_HUNTER_HOOD_T2),
    TRAILBLAZER_TOP_T2(ItemID.TRAILBLAZER_RELIC_HUNTER_TOP_T2),
    TRAILBLAZER_TROUSERS_T2(ItemID.TRAILBLAZER_RELIC_HUNTER_LEGS_T2),
    TRAILBLAZER_BOOTS_T2(ItemID.TRAILBLAZER_RELIC_HUNTER_BOOTS_T2),
    // Trailblazer Relic Hunter (T3)
    TRAILBLAZER_HOOD_T3(ItemID.TRAILBLAZER_RELIC_HUNTER_HOOD_T3),
    TRAILBLAZER_TOP_T3(ItemID.TRAILBLAZER_RELIC_HUNTER_TOP_T3),
    TRAILBLAZER_TROUSERS_T3(ItemID.TRAILBLAZER_RELIC_HUNTER_LEGS_T3),
    TRAILBLAZER_BOOTS_T3(ItemID.TRAILBLAZER_RELIC_HUNTER_BOOTS_T3),
    // Tribal masks
    TRIBAL_MASK(ItemID.BROODOOMASK_POISON),
    TRIBAL_MASK_6337(ItemID.BROODOOMASK_DISEASE),
    TRIBAL_MASK_6339(ItemID.BROODOOMASK_COMBAT),
    // Twisted Relic Hunter (T1)
    TWISTED_HAT_T1(ItemID.TWISTED_RELIC_HUNTER_HAT_T1),
    TWISTED_COAT_T1(ItemID.TWISTED_RELIC_HUNTER_TOP_T1),
    TWISTED_TROUSERS_T1(ItemID.TWISTED_RELIC_HUNTER_LEGS_T1),
    TWISTED_BOOTS_T1(ItemID.TWISTED_RELIC_HUNTER_BOOTS_T1),
    // Twisted Relic Hunter (T2)
    TWISTED_HAT_T2(ItemID.TWISTED_RELIC_HUNTER_HAT_T2),
    TWISTED_COAT_T2(ItemID.TWISTED_RELIC_HUNTER_TOP_T2),
    TWISTED_TROUSERS_T2(ItemID.TWISTED_RELIC_HUNTER_LEGS_T2),
    TWISTED_BOOTS_T2(ItemID.TWISTED_RELIC_HUNTER_BOOTS_T2),
    // Twisted Relic Hunter (T3)
    TWISTED_HAT_T3(ItemID.TWISTED_RELIC_HUNTER_HAT_T3),
    TWISTED_COAT_T3(ItemID.TWISTED_RELIC_HUNTER_TOP_T3),
    TWISTED_TROUSERS_T3(ItemID.TWISTED_RELIC_HUNTER_LEGS_T3),
    TWISTED_BOOTS_T3(ItemID.TWISTED_RELIC_HUNTER_BOOTS_T3),
    // Void knight armour
    VOID_KNIGHT_TOP(ItemID.PEST_VOID_KNIGHT_TOP, true),
    VOID_KNIGHT_ROBE(ItemID.PEST_VOID_KNIGHT_ROBES, true),
    VOID_KNIGHT_GLOVES(ItemID.PEST_VOID_KNIGHT_GLOVES, true),
    // Void knight (Shattered relics ornament kit)
    VOID_KNIGHT_TOP_OR(ItemID.LEAGUE_3_VOID_KNIGHT_TOP, true),
    VOID_KNIGHT_ROBE_OR(ItemID.LEAGUE_3_VOID_KNIGHT_ROBES, true),
    VOID_KNIGHT_GLOVES_OR(ItemID.LEAGUE_3_VOID_KNIGHT_GLOVES, true),
    // Elite void knight
    ELITE_VOID_TOP(ItemID.ELITE_VOID_KNIGHT_TOP, true),
    ELITE_VOID_ROBE(ItemID.ELITE_VOID_KNIGHT_ROBES, true),
    // Elite void knight (Shattered relics ornament kit)
    ELITE_VOID_TOP_OR(ItemID.LEAGUE_3_VOID_KNIGHT_TOP_ELITE, true),
    ELITE_VOID_ROBE_OR(ItemID.LEAGUE_3_VOID_KNIGHT_ROBES_ELITE, true),
    // Void mage/melee/ranger helmets
    VOID_MAGE_HELM(ItemID.GAME_PEST_MAGE_HELM, true),
    VOID_MAGE_HELM_OR(ItemID.LEAGUE_3_VOID_MAGE_HELM, true),
    VOID_MELEE_HELM(ItemID.GAME_PEST_MELEE_HELM, true),
    VOID_MELEE_HELM_OR(ItemID.LEAGUE_3_VOID_MELEE_HELM, true),
    VOID_RANGER_HELM(ItemID.GAME_PEST_ARCHER_HELM, true),
    VOID_RANGER_HELM_OR(ItemID.LEAGUE_3_VOID_RANGE_HELM, true),
    // Vyre noble outfit
    VYRE_NOBLE_TOP(ItemID.VYRELORD_TORSO),
    VYRE_NOBLE_LEGS(ItemID.VYRELORD_LEGS),
    VYRE_NOBLE_SHOES(ItemID.VYRELORD_SHOES),
    // White Knight equipment
    WHITE_FULL_HELM(ItemID.WHITE_FULL_HELM),
    WHITE_PLATEBODY(ItemID.WHITE_PLATEBODY),
    WHITE_PLATESKIRT(ItemID.WHITE_PLATESKIRT),
    WHITE_PLATELEGS(ItemID.WHITE_PLATELEGS),
    WHITE_GLOVES(ItemID.WHITE_GLOVES),
    WHITE_BOOTS(ItemID.WHITE_ARMOURED_BOOTS),
    WHITE_KITESHIELD(ItemID.WHITE_KITESHIELD),
    // Xerician robes
    XERICIAN_HAT(ItemID.XERIC_HAT),
    XERICIAN_TOP(ItemID.XERIC_TOP),
    XERICIAN_ROBE(ItemID.XERIC_ROBE);

    private final int itemID;
    @Getter
    private final String location = "Armour Case";

    @Getter
    private final boolean isBis;


    ArmourCase(int itemID) {
        this.itemID = itemID; this.isBis = false;
    }

    ArmourCase(int itemID, boolean isBis) {
        this.itemID = itemID; this.isBis = isBis;
    }
}
