/*
 * BSD 2-Clause License
 *
 * Copyright (c) 2021, Riley McGee
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package com.wastedbankspace.model.locations;

import com.wastedbankspace.model.StorableItem;
import lombok.Getter;
import net.runelite.api.gameval.ItemID;

@Getter
public enum Bookcase implements StorableItem {
    A_DEAR_FRIEND(ItemID.PRIF_AMLODD_BOOK),
    A_HANDWRITTEN_BOOK(ItemID.EYEGLO_CRYSTAL_BOOK),
    A_TASTE_OF_HOPE(ItemID.DARKMEYER_BOOK),
    ABLENKIANS_ESCAPE(ItemID.ABLENKIAN_ESCAPE),
    ABYSSAL_BOOK(ItemID.RCU_INSTRUCTION_BOOK),
    AIVAS_DIARY(ItemID.LITHKREN_DIARY),
    AKILAS_JOURNAL(ItemID.TOA_BOOK_LOBBY),
    ANCIENT_DIARY(ItemID.FOSSIL_DRAGONKIN_DIARY),
    APMEKENS_CAPTURE(ItemID.TOA_BOOK_BABA),
    ARACHNIDS_OF_VAMPYRIUM(ItemID.TOB_BOOK_NYLOCAS),
    ARCHAEOLOGISTS_DIARY(ItemID.FOSSIL_SWAMP_DIARY),
    ARENA_BOOK(ItemID.MAGICTRAINING_ARENALOREBOOK),
    ASTRONOMY_BOOK(ItemID.BOOK_OF_ASTROLOGY),
    ATLAXS_DIARY(ItemID.GOTR_BOOK),
    AUBURN_VALLEY_ECOLOGICAL_REPORTS(ItemID.AUBURN_ECOLOGICAL_REPORTS),
    BALLAD_OF_THE_BASILISK(ItemID.VIKINGEXILE_BALLAD),
    BATTERED_BOOK(ItemID.ELEMENTAL_WORKSHOP_SHIELD_BOOK),
    BEATEN_BOOK(ItemID.ELEMENTAL_WORKSHOP_HELM_BOOK),
    BIG_BOOK_OF_BANGS(ItemID.REGICIDE_ALCHEMY),
    BINDING_BOOK(ItemID.BOOK_OF_BINDING),
    BIRD_BOOK(ItemID.HUNTING_BOOK_OF_BIRDS),
    BLOODY_DIARY(ItemID.PRIF_ARCLIGHT_BOOK),
    BLOODY_NOTES(ItemID.SHADES_BLOOD_DIARY),
    BOOK(ItemID.THE_SHIELD_OF_ARRAV),
    BOOK_6767(ItemID.RATPITS_MANUAL),
    BOOK_O_PIRACY(ItemID.FEVER_PIRACY_BOOK),
    BOOK_OF_SPYOLOGY(ItemID.MM2_SPY_BOOK),
    BOOK_ON_BAXTORIAN(ItemID.BAXTORIAN_BOOK_WATERFALL_QUEST),
    BOOK_ON_CHEMICALS(ItemID.DIGSITEBOOK),
    BREWIN_GUIDE(ItemID.GAME_BREW_INSTRUCTION_BOOK),
    BURNT_DIARY(ItemID.ROYAL_DIARY1),
    CADARN_LINEAGE(ItemID.ROVING_CADARN_BOOK),
    CLOCKWORK_BOOK(ItemID.PENG_BOOK),
    COCKTAIL_GUIDE(ItemID.COCKTAIL_GUIDE),
    COLLECTION_LOG(ItemID.COLLECTION_LOG),
    CONSTRUCTION_GUIDE(ItemID.POH_GUIDE_BOOK),
    CRAZED_SCRIBBLES(ItemID.PRIF_RANDAS_BOOK),
    CREATURE_KEEPERS_JOURNAL(ItemID.RAIDS_THIEVINGCHEST_BOOK),
    CRONDIS_CAPTURE(ItemID.TOA_BOOK_ZEBAK),
    CRUMBLING_TOME(ItemID.BARROWS_BOOK_HISTORY),
    CRYSTAL_SINGING_FOR_BEGINNERS(ItemID.ROVING_CRYSTAL_BOOK),
    DAGONHAI_HISTORY(ItemID.SUROK_TOME),
    DARK_JOURNAL(ItemID.RAIDS_REWARD_BOOK),
    DEMONIC_TOME(ItemID.AGRITH_BOOK),
    DIARY(ItemID.WITCHES_DIARY),
    DIARY_3395(ItemID.SERUM_BOOK),
    DIARY_3846(ItemID.HORROR_DIARY2),
    DWARVEN_LORE(ItemID.DWARF_ROCK_BOOK),
    EASTERN_DISCOVERY(ItemID.MOURNING_BOOK2),
    EASTERN_SETTLEMENT(ItemID.MOURNING_BOOK3),
    EBRILLS_JOURNAL(ItemID.PRIF_EBRILL_BOOK),
    EDERNS_JOURNAL(ItemID.MOURNING_EDERNS_JOURNAL),
    EMBALMING_MANUAL(ItemID.ICS_LITTLE_BOOKOFEMBALMING),
    ENTOMOLOGISTS_DIARY(ItemID.SLAYER_CAVE_DIARY),
    EXPLORERS_NOTES(ItemID.GODWARS_DWARVEN_BOOK),
    FARMING_MANUAL(ItemID.MYARM_BOOK),
    FEATHERED_JOURNAL(ItemID.EP_TRANSPORT_BOOK01),
    FOSSIL_ISLAND_NOTE_BOOK(ItemID.FOSSIL_NOTE_BOOK),
    GAME_BOOK(ItemID.POH_GAMES_BOOK),
    GHRIMS_BOOK(ItemID.MISC_GHRIMBOOK),
    GIANNES_COOK_BOOK(ItemID.GIANNES_COOK_BOOK),
    GIELINORS_FLORA__ALLOTMENTS(ItemID.FGUILD_BOOK_ALLOTMENTS),
    GIELINORS_FLORA__BUSHES(ItemID.FGUILD_BOOK_BUSHES),
    GIELINORS_FLORA__FLOWERS(ItemID.FGUILD_BOOK_FLOWERS),
    GIELINORS_FLORA__FRUIT(ItemID.FGUILD_BOOK_FRUIT),
    GIELINORS_FLORA__HERBS(ItemID.FGUILD_BOOK_HERBS),
    GIELINORS_FLORA__HOPS(ItemID.FGUILD_BOOK_HOPS),
    GIELINORS_FLORA__TREES(ItemID.FGUILD_BOOK_TREES),
    GLASSBLOWING_BOOK(ItemID.OBSERVATORY_GLASSBLOWING_BOOK),
    GLOUGHS_JOURNAL(ItemID.GRANDTREE_JOURNAL),
    GOBLIN_BOOK(ItemID.SLICE_GOBLIN_HISTORY_BOOK),
    GOBLIN_SYMBOL_BOOK(ItemID.LOST_TRIBE_BOOK),
    GOLLWYNS_FINAL_STATEMENT(ItemID.PRIF_GOLLWYN_BOOK),
    GUIDE_BOOK(ItemID.ARDOUGNE_BOOK),
    HARMONY(ItemID.PRIF_SEREN_BOOK),
    HERMANS_BOOK(ItemID.SWAN_BOOK),
    HETS_CAPTURE(ItemID.TOA_BOOK_AKKHA),
    HISTORIES_OF_THE_HALLOWLAND(ItemID.BURGH_BOOK_HISTORIESOFHALLOWLAND),
    HISTORY_OF_IBAN(ItemID.OLD_JOURNAL),
    HOUNDMASTERS_DIARY(ItemID.RAIDS_HOUNDMASTER_BOOK),
    IMAFORES_BETRAYAL(ItemID.IMAFORE_BETRAYAL),
    IMCANDORIAS_FALL(ItemID.FALL_IMCANDORIA),
    INSTRUCTION_MANUAL(ItemID.MCANNONBOOK),
    JOURNAL_3845(ItemID.HORROR_DIARY1),
    JOURNAL_6755(ItemID.MAKINGHISTORY_JOURNAL),
    KASONDES_JOURNAL(ItemID.TGOD_JOURNAL),
    LEGENDS_OF_THE_MOUNTAIN(ItemID.PRIF_MOUNTAIN_BOOK),
    LITHKREN_VAULT_NOTES(ItemID.DS2_LITHKREN_NOTES_COMPLETE),
    LUTWIDGE_AND_THE_MOONFLY(ItemID.LUTWIDGE_MOONFLY),
    MALUMACS_JOURNAL(ItemID.DS2_KARAMJA_DIARY),
    MANUAL(ItemID.HORROR_DIARY3),
    MODERN_DAY_MORYTANIA(ItemID.BURGH_BOOK_MODERNDAYMORYTANIA),
    MOONCLAN_MANUAL(ItemID.LUNAR_BOOK),
    MOONRISE_WINES(ItemID.ALDARIN_WINE_BOOK),
    MOUNT_KARUULM_DIARY(ItemID.KARUULM_NOTES_BOOK),
    MOVARIOS_NOTES_VOLUME_1(ItemID.WGS_RESEARCHNOTES_1),
    MOVARIOS_NOTES_VOLUME_2(ItemID.WGS_RESEARCHNOTES_2),
    MY_NOTES(ItemID.BRUT_LOGBOOK),
    NEILANS_JOURNAL(ItemID.GA_JOURNAL),
    NIFF__HARRY(ItemID.PRIF_POEM_SCROLL),
    NISTIRIOS_MANIFESTO(ItemID.RAIDS_VASANISTIRIO_BOOK),
    ODE_TO_ETERNITY(ItemID.SOTE_BAXTORIAN_BOOK),
    OHNS_DIARY(ItemID.SNAKEBOSS_BOOK),
    OLD_DIARY(ItemID.MYQ4_SERAFINA_BOOK),
    OLD_JOURNAL(ItemID.UPASS_JOURNAL),
    ON_LEPRECHAUNS(ItemID.PRIF_LEPRECHAUN_BOOK),
    ON_MIGRATION_PATTERNS(ItemID.CUSTODIAN_LOREBOOK),
    OVERSEERS_BOOK(ItemID.ABYSSALSIRE_BOOK),
    PIE_RECIPE_BOOK(ItemID.BOOK_RECIPIE_PIE),
    PRAYER_BOOK(ItemID.BRAIN_FOG_BOOK),
    PRIFDDINAS_HISTORY(ItemID.MOURNING_BOOK1),
    QUEEN_HELP_BOOK(ItemID.BARBASSAULT_QUEEN_GUIDEBOOK),
    SACRAMENTS_OF_ENT_FOLK(ItemID.ENT_TOTEMS_INTRO_BOOK),
    SCABARAS_CAPTURE(ItemID.TOA_BOOK_KEPHRI),
    SECURITY_BOOK(ItemID.SOS_SECURITY_BOOK),
    SERAFINA(ItemID.TALE_SERAFINA),
    SERAFINAS_DIARY(ItemID.TOB_BOOK_MAIDEN),
    SHAMANS_TOME(ItemID.SHAMANS_TOME),
    SINKETHS_DIARY(ItemID.SUROK_DIARY),
    SOGGY_JOURNAL(ItemID.PRIF_SOGGY_BOOK),
    SOUL_WARS_GUIDE(ItemID.SOUL_WARS_TUT_BOOK),
    SPIRIT_ANGLERS_RESEARCH_NOTES(ItemID.TEMPOROSS_BOOK_RESEARCH_NOTES),
    STAINED_JOURNAL(ItemID.PRIF_ZULRAH_BOOK),
    STRANGE_HALLOWED_TOME(ItemID.HALLOWED_TOME),
    STRONGHOLD_NOTES(ItemID.SOS_STRONGHOLD_BOOK),
    TARNS_DIARY(ItemID.LOTR_DIARY),
    TEKTONS_JOURNAL(ItemID.RAIDS_TEKTON_BOOK),
    THE_BUTCHER(ItemID.TOB_BOOK_BLOAT),
    THE_DESERT_TROUT__SHIPS_LOG(ItemID.TEMPOROSS_BOOK_SHIPS_LOG),
    THE_EIGHT_CLANS(ItemID.PRIF_HYMN_SCROLL),
    THE_GREAT_DIVIDE(ItemID.MOURNING_BOOK4),
    THE_HUEYCOATL(ItemID.HUEYCOATL_BOOK),
    THE_JACKALS_TORCH(ItemID.TOA_BOOK_ICTHLARIN),
    THE_LIVING_STATUES(ItemID.PRIF_GARGOYLE_BOOK),
    THE_SHADOW_REALM(ItemID.TOB_BOOK_SOTETSEG),
    THE_SLEEPING_SEVEN(ItemID.BURGH_BOOK_SEVENWARRIORS),
    THE_SPURNED_DEMON(ItemID.PRIF_ZALCANO_BOOK),
    THE_TRUTH_BEHIND_THE_MYTH_EXCERPT(ItemID.PRIF_CAMORRA_BOOK),
    THE_WARDENS(ItemID.TOA_BOOK_WARDENS),
    THE_WEEPING(ItemID.THE_WEEPING),
    THE_WILD_HUNT(ItemID.TOB_BOOK_XARPUS),
    TOME_OF_THE_MOON(ItemID.HOSDUN_MOON_TOME),
    TOME_OF_THE_SUN(ItemID.HOSDUN_SUN_TOME),
    TOME_OF_THE_TEMPLE(ItemID.HOSDUN_TEMPLE_TOME),
    TRANSDIMENSIONAL_NOTES(ItemID.RAIDS_VESPULA_BOOK),
    TRANSLATION(ItemID.FOUR_DIAMONDS_TRANSLATION_PRIMER),
    TRANSLATION_BOOK(ItemID.GRANDTREE_TRANSLATIONBOOK),
    TREE_WIZARDS_JOURNAL(ItemID.SHADES_SWAMP_DIARY),
    UNGAEL_LAB_NOTES(ItemID.DS2_UNGAEL_NOTES_COMPLETE),
    VANGUARD_JUDGEMENT(ItemID.RAIDS_VANGUARD_BOOK),
    VARLAMORE_ENVOY(ItemID.HOSIDIUSQUEST_BOOK),
    VARMENS_NOTES(ItemID.GOLEM_NOTES),
    VERZIK_VITUR__PATIENT_RECORD(ItemID.TOB_BOOK_VERZIK),
    WEISS_FIRE_NOTES(ItemID.MY2ARM_BOOK),
    YEWNOCKS_NOTES(ItemID.POG_YEWNOCKS_NOTE);

    private final int itemID;
    @Getter
    private final String location = "Bookcase";

    @Getter
    private final boolean isBis;

    Bookcase(int itemID)
    {
        this.itemID = itemID;
        this.isBis = false;
    }
}
