/*
 * BSD 2-Clause License
 *
 * Copyright (c) 2021, Riley McGee
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package com.wastedbankspace.model.locations;

import com.wastedbankspace.model.StorableItem;
import lombok.Getter;
import net.runelite.api.gameval.ItemID;

@Getter
public enum CapeRack implements StorableItem {
    ACHIEVEMENT_DIARY_HOOD(ItemID.SKILLCAPE_AD_HOOD),
    ACHIEVEMENT_DIARY_CAPE(ItemID.SKILLCAPE_AD, true),
    ACHIEVEMENT_DIARY_CAPE_T(ItemID.SKILLCAPE_AD_TRIMMED, true),
    AGILITY_HOOD(ItemID.SKILLCAPE_AGILITY_HOOD),
    AGILITY_CAPE(ItemID.SKILLCAPE_AGILITY, true),
    AGILITY_CAPET(ItemID.SKILLCAPE_AGILITY_TRIMMED, true),
    ATTACK_HOOD(ItemID.SKILLCAPE_ATTACK_HOOD),
    ATTACK_CAPE(ItemID.SKILLCAPE_ATTACK, true),
    ATTACK_CAPET(ItemID.SKILLCAPE_ATTACK_TRIMMED, true),
    CHAMPIONS_CAPE(ItemID.CHAMPION_CAPE, true),
    CONSTRUCT_HOOD(ItemID.SKILLCAPE_CONSTRUCTION_HOOD),
    CONSTRUCT_CAPE(ItemID.SKILLCAPE_CONSTRUCTION, true),
    CONSTRUCT_CAPET(ItemID.SKILLCAPE_CONSTRUCTION_TRIMMED, true),
    COOKING_HOOD(ItemID.SKILLCAPE_COOKING_HOOD),
    COOKING_CAPE(ItemID.SKILLCAPE_COOKING, true),
    COOKING_CAPET(ItemID.SKILLCAPE_COOKING_TRIMMED, true),
    CRAFTING_HOOD(ItemID.SKILLCAPE_CRAFTING_HOOD),
    CRAFTING_CAPE(ItemID.SKILLCAPE_CRAFTING, true),
    CRAFTING_CAPET(ItemID.SKILLCAPE_CRAFTING_TRIMMED, true),
    DEFENCE_HOOD(ItemID.SKILLCAPE_DEFENCE_HOOD),
    DEFENCE_CAPE(ItemID.SKILLCAPE_DEFENCE, true),
    DEFENCE_CAPET(ItemID.SKILLCAPE_DEFENCE_TRIMMED, true),
    FARMING_HOOD(ItemID.SKILLCAPE_FARMING_HOOD),
    FARMING_CAPE(ItemID.SKILLCAPE_FARMING, true),
    FARMING_CAPET(ItemID.SKILLCAPE_FARMING_TRIMMED, true),
    FIRE_CAPE(ItemID.TZHAAR_CAPE_FIRE, true),
    // Trouver parchmented Fire cape; can be store alongside regular fire cape
    FIRE_CAPE_L(ItemID.TZHAAR_CAPE_FIRE_TROUVER, true),
    FIREMAKING_HOOD(ItemID.SKILLCAPE_FIREMAKING_HOOD),
    FIREMAKING_CAPE(ItemID.SKILLCAPE_FIREMAKING, true),
    FIREMAKING_CAPET(ItemID.SKILLCAPE_FIREMAKING_TRIMMED, true),
    FISHING_HOOD(ItemID.SKILLCAPE_FISHING_HOOD),
    FISHING_CAPE(ItemID.SKILLCAPE_FISHING, true),
    FISHING_CAPET(ItemID.SKILLCAPE_FISHING_TRIMMED, true),
    FLETCHING_HOOD(ItemID.SKILLCAPE_FLETCHING_HOOD),
    FLETCHING_CAPE(ItemID.SKILLCAPE_FLETCHING, true),
    FLETCHING_CAPET(ItemID.SKILLCAPE_FLETCHING_TRIMMED, true),
    GAUNTLET_CAPE(ItemID.GAUNTLET_CRYSTALLINE_CAPE),
    HERBLORE_HOOD(ItemID.SKILLCAPE_HERBLORE_HOOD),
    HERBLORE_CAPE(ItemID.SKILLCAPE_HERBLORE, true),
    HERBLORE_CAPET(ItemID.SKILLCAPE_HERBLORE_TRIMMED, true),
    HITPOINTS_HOOD(ItemID.SKILLCAPE_HITPOINTS_HOOD),
    HITPOINTS_CAPE(ItemID.SKILLCAPE_HITPOINTS, true),
    HITPOINTS_CAPET(ItemID.SKILLCAPE_HITPOINTS_TRIMMED, true),
    HUNTER_HOOD_PoHCapeRack(ItemID.SKILLCAPE_HUNTING_HOOD),
    HUNTER_CAPE_PoHCapeRack(ItemID.SKILLCAPE_HUNTING, true),
    HUNTER_CAPET_PoHCapeRack(ItemID.SKILLCAPE_HUNTING_TRIMMED, true),
    ICTHLARINS_SHROUD_TIER_1(ItemID.ICTHLARINS_SHROUD_1),
    ICTHLARINS_SHROUD_TIER_2(ItemID.ICTHLARINS_SHROUD_2),
    ICTHLARINS_SHROUD_TIER_3(ItemID.ICTHLARINS_SHROUD_3),
    ICTHLARINS_SHROUD_TIER_4(ItemID.ICTHLARINS_SHROUD_4),
    ICTHLARINS_SHROUD_TIER_5(ItemID.ICTHLARINS_SHROUD_5),
    INFERNAL_CAPE(ItemID.INFERNAL_CAPE, true),
    INFERNAL_CAPE_L(ItemID.INFERNAL_CAPE_TROUVER, true), // trouver parchmented
    CAPE_OF_LEGENDS(ItemID.CAPE_OF_LEGENDS),
    GUTHIX_CAPE(ItemID.GUTHIX_CAPE),
    IMBUED_GUTHIX_CAPE(ItemID.MA2_GUTHIX_CAPE, true),
    IMBUED_GUTHIX_CAPE_L(ItemID.MA2_GUTHIX_CAPE_TROUVER, true), // trouver parchmented
    IMBUED_GUTHIX_CAPE_DEADMAN(ItemID.DEADMAN_MA2_GUTHIX_CAPE, true),
    SARADOMIN_CAPE(ItemID.SARADOMIN_CAPE),
    IMBUED_SARADOMIN_CAPE(ItemID.MA2_SARADOMIN_CAPE, true),
    IMBUED_SARADOMIN_CAPE_L(ItemID.MA2_SARADOMIN_CAPE_TROUVER, true), // trouver parchmented
    IMBUED_SARADOMIN_CAPE_DEADMAN(ItemID.DEADMAN_MA2_SARADOMIN_CAPE, true),
    ZAMORAK_CAPE(ItemID.ZAMORAK_CAPE),
    IMBUED_ZAMORAK_CAPE(ItemID.MA2_ZAMORAK_CAPE, true),
    IMBUED_ZAMORAK_CAPE_L(ItemID.MA2_ZAMORAK_CAPE_TROUVER, true), // trouver parchmented
    IMBUED_ZAMORAK_CAPE_DEADMAN(ItemID.DEADMAN_MA2_ZAMORAK_CAPE, true),
    MAGIC_HOOD(ItemID.SKILLCAPE_MAGIC_HOOD),
    MAGIC_CAPE(ItemID.SKILLCAPE_MAGIC, true),
    MAGIC_CAPET(ItemID.SKILLCAPE_MAGIC_TRIMMED, true),
    // MAX CAPES
    MAX_HOOD(ItemID.SKILLCAPE_MAX_HOOD),
    MAX_CAPE(ItemID.SKILLCAPE_MAX, true),
    ARDOUGNE_MAX_HOOD(ItemID.SKILLCAPE_MAX_HOOD_ARDY),
    ARDOUGNE_MAX_CAPE(ItemID.SKILLCAPE_MAX_ARDY, true),
    ACCUMULATOR_MAX_HOOD(ItemID.SKILLCAPE_MAX_HOOD_ANMA),
    ACCUMULATOR_MAX_CAPE(ItemID.SKILLCAPE_MAX_ANMA, true),
    ASSEMBLER_MAX_HOOD(ItemID.SKILLCAPE_MAX_HOOD_ASSEMBLER),
    ASSEMBLER_MAX_CAPE(ItemID.SKILLCAPE_MAX_ASSEMBLER, true),
    ASSEMBLER_MAX_CAPE_L(ItemID.SKILLCAPE_MAX_ASSEMBLER_TROUVER, true), // trouver parchmented
    DIZANAS_MAX_HOOD(ItemID.SKILLCAPE_MAX_HOOD_DIZANAS),
    DIZANAS_MAX_CAPE(ItemID.SKILLCAPE_MAX_DIZANAS, true),
    FIRE_MAX_HOOD(ItemID.SKILLCAPE_MAX_HOOD_FIRECAPE),
    FIRE_MAX_CAPE(ItemID.SKILLCAPE_MAX_FIRECAPE, true),
    FIRE_MAX_CAPE_L(ItemID.SKILLCAPE_MAX_FIRECAPE_TROUVER, true), // trouver parchmented
    INFERNAL_MAX_HOOD(ItemID.SKILLCAPE_MAX_HOOD_INFERNALCAPE),
    INFERNAL_MAX_CAPE(ItemID.SKILLCAPE_MAX_INFERNALCAPE_DUMMY, true),
    INFERNAL_MAX_CAPE_L(ItemID.SKILLCAPE_MAX_INFERNALCAPE_TROUVER, true), // trouver parchmented
    IMBUED_GUTHIX_MAX_HOOD(ItemID.SKILLCAPE_MAX_HOOD_GUTHIX2),
    IMBUED_GUTHIX_MAX_CAPE(ItemID.SKILLCAPE_MAX_GUTHIX2, true),
    IMBUED_GUTHIX_MAX_CAPE_L(ItemID.SKILLCAPE_MAX_GUTHIX2_TROUVER, true), // trouver parchmented
    IMBUED_SARADOMIN_MAX_HOOD(ItemID.SKILLCAPE_MAX_HOOD_SARADOMIN2),
    IMBUED_SARADOMIN_MAX_CAPE(ItemID.SKILLCAPE_MAX_SARADOMIN2, true),
    IMBUED_SARADOMIN_MAX_CAPE_L(ItemID.SKILLCAPE_MAX_SARADOMIN2_TROUVER, true), // trouver parchmented
    IMBUED_ZAMORAK_MAX_HOOD(ItemID.SKILLCAPE_MAX_HOOD_ZAMORAK2),
    IMBUED_ZAMORAK_MAX_CAPE(ItemID.SKILLCAPE_MAX_ZAMORAK2, true),
    IMBUED_ZAMORAK_MAX_CAPE_L(ItemID.SKILLCAPE_MAX_ZAMORAK2_TROUVER, true), // trouver parchmented
    MASORI_ASSEMBLER_MAX_HOOD(ItemID.SKILLCAPE_MAX_HOOD_ASSEMBLER_MASORI),
    MASORI_ASSEMBLER_MAX_CAPE(ItemID.SKILLCAPE_MAX_ASSEMBLER_MASORI, true),
    MASORI_ASSEMBLER_MAX_CAPE_L(ItemID.SKILLCAPE_MAX_ASSEMBLER_MASORI_TROUVER, true), // trouver parchmented
    MYTHICAL_MAX_HOOD(ItemID.SKILLCAPE_MAX_HOOD_MYTHICAL),
    MYTHICAL_MAX_CAPE(ItemID.SKILLCAPE_MAX_MYTHICAL, true),
    GUTHIX_MAX_HOOD(ItemID.SKILLCAPE_MAX_HOOD_GUTHIX),
    GUTHIX_MAX_CAPE(ItemID.SKILLCAPE_MAX_GUTHIX, true),
    SARADOMIN_MAX_HOOD_MAX_CAPE(ItemID.SKILLCAPE_MAX_HOOD_SARADOMIN),
    SARADOMIN_MAX_CAPE(ItemID.SKILLCAPE_MAX_SARADOMIN, true),
    ZAMORAK_MAX_HOOD(ItemID.SKILLCAPE_MAX_HOOD_ZAMORAK),
    ZAMORAK_MAX_CAPE(ItemID.SKILLCAPE_MAX_ZAMORAK, true),

    MINING_HOOD(ItemID.SKILLCAPE_MINING_HOOD),
    MINING_CAPE(ItemID.SKILLCAPE_MINING, true),
    MINING_CAPET(ItemID.SKILLCAPE_MINING_TRIMMED, true),
    MUSIC_HOOD(ItemID.MUSIC_CAPE_HOOD),
    MUSIC_CAPE(ItemID.MUSIC_CAPE, true),
    MUSIC_CAPET(ItemID.MUSIC_CAPE_TRIMMED, true),
    MYTHICAL_CAPE(ItemID.POH_TROPHY_MYTHICAL_CAPE, true),
    OBSIDIAN_CAPE(ItemID.TZHAAR_CAPE_OBSIDIAN),
    PRAYER_HOOD(ItemID.SKILLCAPE_PRAYER_HOOD),
    PRAYER_CAPE(ItemID.SKILLCAPE_PRAYER, true),
    PRAYER_CAPET(ItemID.SKILLCAPE_PRAYER_TRIMMED, true),
    QUEST_POINT_HOOD(ItemID.SKILLCAPE_QP_HOOD),
    QUEST_POINT_CAPE(ItemID.SKILLCAPE_QP, true),
    QUEST_POINT_CAPE_T(ItemID.SKILLCAPE_QP_TRIMMED, true),
    RANGING_HOOD(ItemID.SKILLCAPE_RANGING_HOOD),
    RANGING_CAPE(ItemID.SKILLCAPE_RANGING, true),
    RANGING_CAPET(ItemID.SKILLCAPE_RANGING_TRIMMED, true),
    RUNECRAFT_HOOD(ItemID.SKILLCAPE_RUNECRAFTING_HOOD),
    RUNECRAFT_CAPE(ItemID.SKILLCAPE_RUNECRAFTING, true),
    RUNECRAFT_CAPET(ItemID.SKILLCAPE_RUNECRAFTING_TRIMMED, true),
    SINHAZA_SHROUD_TIER_1(ItemID.SINHAZA_SHROUD_TIER1),
    SINHAZA_SHROUD_TIER_2(ItemID.SINHAZA_SHROUD_TIER2),
    SINHAZA_SHROUD_TIER_3(ItemID.SINHAZA_SHROUD_TIER3),
    SINHAZA_SHROUD_TIER_4(ItemID.SINHAZA_SHROUD_TIER4),
    SINHAZA_SHROUD_TIER_5(ItemID.SINHAZA_SHROUD_TIER5),
    SLAYER_HOOD(ItemID.SKILLCAPE_SLAYER_HOOD),
    SLAYER_CAPE(ItemID.SKILLCAPE_SLAYER, true),
    SLAYER_CAPET(ItemID.SKILLCAPE_SLAYER_TRIMMED, true),
    SMITHING_HOOD(ItemID.SKILLCAPE_SMITHING_HOOD),
    SMITHING_CAPE(ItemID.SKILLCAPE_SMITHING, true),
    SMITHING_CAPET(ItemID.SKILLCAPE_SMITHING_TRIMMED, true),
    SOUL_CAPE(ItemID.SOUL_CAPE_RED),
    SOUL_CAPE_25346(ItemID.SOUL_CAPE_BLUE),
    SPOTTED_CAPE(ItemID.HUNTING_LIGHT_CAPE),
    SPOTTIER_CAPE(ItemID.HUNTING_LIGHTER_CAPE),
    STRENGTH_HOOD(ItemID.SKILLCAPE_STRENGTH_HOOD),
    STRENGTH_CAPE(ItemID.SKILLCAPE_STRENGTH, true),
    STRENGTH_CAPET(ItemID.SKILLCAPE_STRENGTH_TRIMMED, true),
    THIEVING_HOOD(ItemID.SKILLCAPE_THIEVING_HOOD),
    THIEVING_CAPE(ItemID.SKILLCAPE_THIEVING, true),
    THIEVING_CAPET(ItemID.SKILLCAPE_THIEVING_TRIMMED, true),
    VICTORS_CAPE_1(ItemID.BR_CAPE_1),
    VICTORS_CAPE_10(ItemID.BR_CAPE_10),
    VICTORS_CAPE_50(ItemID.BR_CAPE_50),
    VICTORS_CAPE_100(ItemID.BR_CAPE_100),
    VICTORS_CAPE_500(ItemID.BR_CAPE_500),
    VICTORS_CAPE_1000(ItemID.BR_CAPE_1000),
    // TEAM CAPE, only one team cape can be stored
    TEAM1_CAPE(ItemID.WILDERNESS_CAPE_1),
    TEAM2_CAPE(ItemID.WILDERNESS_CAPE_2),
    TEAM3_CAPE(ItemID.WILDERNESS_CAPE_3),
    TEAM4_CAPE(ItemID.WILDERNESS_CAPE_4),
    TEAM5_CAPE(ItemID.WILDERNESS_CAPE_5),
    TEAM6_CAPE(ItemID.WILDERNESS_CAPE_6),
    TEAM7_CAPE(ItemID.WILDERNESS_CAPE_7),
    TEAM8_CAPE(ItemID.WILDERNESS_CAPE_8),
    TEAM9_CAPE(ItemID.WILDERNESS_CAPE_9),
    TEAM10_CAPE(ItemID.WILDERNESS_CAPE_10),
    TEAM11_CAPE(ItemID.WILDERNESS_CAPE_11),
    TEAM12_CAPE(ItemID.WILDERNESS_CAPE_12),
    TEAM13_CAPE(ItemID.WILDERNESS_CAPE_13),
    TEAM14_CAPE(ItemID.WILDERNESS_CAPE_14),
    TEAM15_CAPE(ItemID.WILDERNESS_CAPE_15),
    TEAM16_CAPE(ItemID.WILDERNESS_CAPE_16),
    TEAM17_CAPE(ItemID.WILDERNESS_CAPE_17),
    TEAM18_CAPE(ItemID.WILDERNESS_CAPE_18),
    TEAM19_CAPE(ItemID.WILDERNESS_CAPE_19),
    TEAM20_CAPE(ItemID.WILDERNESS_CAPE_20),
    TEAM21_CAPE(ItemID.WILDERNESS_CAPE_21),
    TEAM22_CAPE(ItemID.WILDERNESS_CAPE_22),
    TEAM23_CAPE(ItemID.WILDERNESS_CAPE_23),
    TEAM24_CAPE(ItemID.WILDERNESS_CAPE_24),
    TEAM25_CAPE(ItemID.WILDERNESS_CAPE_25),
    TEAM26_CAPE(ItemID.WILDERNESS_CAPE_26),
    TEAM27_CAPE(ItemID.WILDERNESS_CAPE_27),
    TEAM28_CAPE(ItemID.WILDERNESS_CAPE_28),
    TEAM29_CAPE(ItemID.WILDERNESS_CAPE_29),
    TEAM30_CAPE(ItemID.WILDERNESS_CAPE_30),
    TEAM31_CAPE(ItemID.WILDERNESS_CAPE_31),
    TEAM32_CAPE(ItemID.WILDERNESS_CAPE_32),
    TEAM33_CAPE(ItemID.WILDERNESS_CAPE_33),
    TEAM34_CAPE(ItemID.WILDERNESS_CAPE_34),
    TEAM35_CAPE(ItemID.WILDERNESS_CAPE_35),
    TEAM36_CAPE(ItemID.WILDERNESS_CAPE_36),
    TEAM37_CAPE(ItemID.WILDERNESS_CAPE_37),
    TEAM38_CAPE(ItemID.WILDERNESS_CAPE_38),
    TEAM39_CAPE(ItemID.WILDERNESS_CAPE_39),
    TEAM40_CAPE(ItemID.WILDERNESS_CAPE_40),
    TEAM41_CAPE(ItemID.WILDERNESS_CAPE_41),
    TEAM42_CAPE(ItemID.WILDERNESS_CAPE_42),
    TEAM43_CAPE(ItemID.WILDERNESS_CAPE_43),
    TEAM44_CAPE(ItemID.WILDERNESS_CAPE_44),
    TEAM45_CAPE(ItemID.WILDERNESS_CAPE_45),
    TEAM46_CAPE(ItemID.WILDERNESS_CAPE_46),
    TEAM47_CAPE(ItemID.WILDERNESS_CAPE_47),
    TEAM48_CAPE(ItemID.WILDERNESS_CAPE_48),
    TEAM49_CAPE(ItemID.WILDERNESS_CAPE_49),
    TEAM50_CAPE(ItemID.WILDERNESS_CAPE_50),

    TEAM_CAPE_ZERO(ItemID.WILDERNESS_CAPE_ZERO),
    TEAM_CAPE_I(ItemID.WILDERNESS_CAPE_I),
    TEAM_CAPE_X(ItemID.WILDERNESS_CAPE_X),

    WOODCUTTING_HOOD(ItemID.SKILLCAPE_WOODCUTTING_HOOD),
    WOODCUTTING_CAPE_2(ItemID.SKILLCAPE_WOODCUTTING, true),
    WOODCUTTING_CAPE_T(ItemID.SKILLCAPE_WOODCUTTING_TRIMMED, true),

    XERICS_CHAMPION(ItemID.COX_CHALLENGE_CAPE_T5),
    XERICS_GENERAL(ItemID.COX_CHALLENGE_CAPE_T4),
    XERICS_GUARD(ItemID.COX_CHALLENGE_CAPE_T1),
    XERICS_SENTINEL(ItemID.COX_CHALLENGE_CAPE_T3),
    XERICS_WARRIOR(ItemID.COX_CHALLENGE_CAPE_T2);

    private final int itemID;
    @Getter
    private final String location = "Cape Rack";

    @Getter
    private final boolean isBis;

    CapeRack(int itemID) {
        this.itemID = itemID;
        this.isBis = false;
    }
    CapeRack(int itemID, boolean isBis) {
        this.itemID = itemID; this.isBis = isBis;
    }
}
