/*
 * BSD 2-Clause License
 *
 * Copyright (c) 2021, Riley McGee
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package com.wastedbankspace.model.locations;

import com.wastedbankspace.model.StorableItem;
import lombok.Getter;
import net.runelite.api.gameval.ItemID;

@Getter
public enum FossilStorage implements StorableItem {
    UNIDENTIFIED_SMALL_FOSSIL(ItemID.FOSSIL_SMALL_UNID),
    SMALL_FOSSILISED_LIMBS(ItemID.FOSSIL_SMALL_1),
    SMALL_FOSSILISED_SPINE(ItemID.FOSSIL_SMALL_2),
    SMALL_FOSSILISED_RIBS(ItemID.FOSSIL_SMALL_3),
    SMALL_FOSSILISED_PELVIS(ItemID.FOSSIL_SMALL_4),
    SMALL_FOSSILISED_SKULL(ItemID.FOSSIL_SMALL_5),
    UNIDENTIFIED_MEDIUM_FOSSIL(ItemID.FOSSIL_MEDIUM_UNID),
    MEDIUM_FOSSILISED_LIMBS(ItemID.FOSSIL_MEDIUM_1),
    MEDIUM_FOSSILISED_SPINE(ItemID.FOSSIL_MEDIUM_2),
    MEDIUM_FOSSILISED_RIBS(ItemID.FOSSIL_MEDIUM_3),
    MEDIUM_FOSSILISED_PELVIS(ItemID.FOSSIL_MEDIUM_4),
    MEDIUM_FOSSILISED_SKULL(ItemID.FOSSIL_MEDIUM_5),
    UNIDENTIFIED_LARGE_FOSSIL(ItemID.FOSSIL_LARGE_UNID),
    LARGE_FOSSILISED_LIMBS(ItemID.FOSSIL_LARGE_1),
    LARGE_FOSSILISED_SPINE(ItemID.FOSSIL_LARGE_2),
    LARGE_FOSSILISED_RIBS(ItemID.FOSSIL_LARGE_3),
    LARGE_FOSSILISED_PELVIS(ItemID.FOSSIL_LARGE_4),
    LARGE_FOSSILISED_SKULL(ItemID.FOSSIL_LARGE_5),
    FOSSILISED_ROOTS(ItemID.FOSSIL_PLANT_1),
    FOSSILISED_STUMP(ItemID.FOSSIL_PLANT_2),
    FOSSILISED_BRANCH(ItemID.FOSSIL_PLANT_3),
    FOSSILISED_LEAF(ItemID.FOSSIL_PLANT_4),
    FOSSILISED_MUSHROOM(ItemID.FOSSIL_PLANT_5),
    UNIDENTIFIED_RARE_FOSSIL(ItemID.FOSSIL_RARE_UNID),
    RARE_FOSSILISED_LIMBS(ItemID.FOSSIL_RARE_1),
    RARE_FOSSILISED_PELVIS(ItemID.FOSSIL_RARE_4),
    RARE_FOSSILISED_RIBS(ItemID.FOSSIL_RARE_3),
    RARE_FOSSILISED_SKULL(ItemID.FOSSIL_RARE_5),
    RARE_FOSSILISED_SPINE(ItemID.FOSSIL_RARE_2),
    RARE_FOSSILISED_TUSK(ItemID.FOSSIL_RARE_6);

    private final int itemID;
    @Getter
    private final String location = "Fossil Storage";
    @Getter
    private final boolean isBis;

    FossilStorage(int itemID) {
        this.itemID = itemID;
        this.isBis = false;
    }
}
