/*
 * BSD 2-Clause License
 *
 * Copyright (c) 2021, Riley McGee
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package com.wastedbankspace.model.locations;

import com.wastedbankspace.model.StorableItem;
import lombok.Getter;
import net.runelite.api.gameval.ItemID;

@Getter
public enum HuntsmansKit implements StorableItem {
    BIRD_SNARE(ItemID.HUNTING_OJIBWAY_BIRD_SNARE),
    NOOSE_WAND(ItemID.NOOSE_WAND),
    BUTTERFLY_NET_(ItemID.HUNTING_BUTTERFLY_NET),
    MAGIC_BUTTERFLY_NET_(ItemID.II_MAGIC_BUTTERFLY_NET),
    BUTTERFLY_JAR_(ItemID.BUTTERFLY_JAR),
    BOX_TRAP(ItemID.HUNTING_BOX_TRAP),
    RABBIT_SNARE(ItemID.HUNTING_SNARE),
    UNLIT_TORCH(ItemID.TORCH_UNLIT),
    SMALL_FISHING_NET_(ItemID.NET),
    ROPE(ItemID.ROPE),
    MAGIC_BOX(ItemID.MAGIC_IMP_BOX),
    IMPINABOX1(ItemID.MAGIC_IMP_BOX_HALF),
    IMPINABOX2(ItemID.MAGIC_IMP_BOX_FULL),
    TEASING_STICK(ItemID.HUNTING_TEASING_STICK),
    HUNTERS_SPEAR(ItemID.HG_HUNTER_SPEAR),
    WOOD_CAMO_TOP_(ItemID.HUNTING_CAMOFLAUGE_ROBE_WOOD),
    WOOD_CAMO_LEGS_(ItemID.HUNTING_TROUSERS_WOOD),
    POLAR_CAMO_TOP_(ItemID.HUNTING_CAMOFLAUGE_ROBE_POLAR),
    POLAR_CAMO_LEGS_(ItemID.HUNTING_TROUSERS_POLAR),
    JUNGLE_CAMO_TOP_(ItemID.HUNTING_CAMOFLAUGE_ROBE_JUNGLE),
    JUNGLE_CAMO_LEGS_(ItemID.HUNTING_TROUSERS_JUNGLE),
    DESERT_CAMO_TOP_(ItemID.HUNTING_CAMOFLAUGE_ROBE_DESERT),
    DESERT_CAMO_LEGS_(ItemID.HUNTING_TROUSERS_DESERT),
    LARUPIA_HAT_(ItemID.HUNTING_HAT_JAGUAR),
    LARUPIA_TOP_(ItemID.HUNTING_TORSO_JAGUAR),
    LARUPIA_LEGS_(ItemID.HUNTING_TROUSERS_JAGUAR),
    GRAAKH_HEADDRESS(ItemID.HUNTING_HAT_LEOPARD),
    GRAAKH_TOP(ItemID.HUNTING_TORSO_LEOPARD),
    GRAAKH_LEGS(ItemID.HUNTING_TROUSERS_LEOPARD),
    KYATT_HAT_(ItemID.HUNTING_HAT_TIGER),
    KYATT_TOP_(ItemID.HUNTING_TORSO_TIGER),
    KYATT_LEGS_(ItemID.HUNTING_TROUSERS_TIGER),
    HUNTER_HOOD(ItemID.SKILLCAPE_HUNTING_HOOD),
    HUNTER_CAPE(ItemID.SKILLCAPE_HUNTING),
    HUNTER_CAPET(ItemID.SKILLCAPE_HUNTING_TRIMMED),
    GUILD_HUNTER_HEADWEAR(ItemID.HG_HUNTER_HOOD),
    GUILD_HUNTER_TOP(ItemID.HG_HUNTER_TOP),
    GUILD_HUNTER_LEGS(ItemID.HG_HUNTER_LEGS),
    GUILD_HUNTER_BOOTS(ItemID.HG_HUNTER_BOOTS),
    RING_OF_PURSUIT(ItemID.RING_OF_PURSUIT),
    IMPLING_JAR_(ItemID.II_IMPLING_JAR);

    private final int itemID;
    @Getter
    private final String location = "Huntsman's Kit";
    @Getter
    private final boolean isBis;

    HuntsmansKit(int itemID) {
        this.itemID = itemID;
        this.isBis = false;
    }
}
