/*
 * BSD 2-Clause License
 *
 * Copyright (c) 2021, Riley McGee
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package com.wastedbankspace.model.locations;

import com.wastedbankspace.model.StorableItem;
import lombok.Getter;
import net.runelite.api.gameval.ItemID;

@Getter
public enum MagicWardrobe implements StorableItem {
    // Amy's Saw
    AMYS_SAW(ItemID.WEARABLE_SAW, true),
    AMYS_SAW_OFFHAND(ItemID.WEARABLE_SAW_OFFHAND, true),
    // Ancestral Robes
    ANCESTRAL_HAT(ItemID.ANCESTRAL_HAT, true),
    ANCESTRAL_ROBE_BOTTOM(ItemID.ANCESTRAL_ROBE_BOTTOM, true),
    ANCESTRAL_ROBE_TOP(ItemID.ANCESTRAL_ROBE_TOP, true),
    // TwistedAncestral Robes
    TWISTED_ANCESTRAL_HAT(ItemID.ANCESTRAL_HAT_TWISTED, true),
    TWISTED_ANCESTRAL_ROBE_BOTTOM(ItemID.ANCESTRAL_ROBE_BOTTOM_TWISTED, true),
    TWISTED_ANCESTRAL_ROBE_TOP(ItemID.ANCESTRAL_ROBE_TOP_TWISTED, true),
    // Ancient ceremonial robes
    ANCIENT_CEREMONIAL_BOOTS(ItemID.ANCIENT_CEREMONIAL_BOOTS),
    ANCIENT_CEREMONIAL_GLOVES(ItemID.ANCIENT_CEREMONIAL_GLOVES),
    ANCIENT_CEREMONIAL_LEGS(ItemID.ANCIENT_CEREMONIAL_LEGS),
    ANCIENT_CEREMONIAL_MASK(ItemID.ANCIENT_CEREMONIAL_MASK),
    ANCIENT_CEREMONIAL_TOP(ItemID.ANCIENT_CEREMONIAL_TOP),
    // Bloodbark armour
    BLOODBARK_BODY(ItemID.BLOODBARK_BODY),
    BLOODBARK_BOOTS(ItemID.BLOODBARK_GREAVES),
    BLOODBARK_GAUNTLETS(ItemID.BLOODBARK_GAUNTLETS),
    BLOODBARK_HELM(ItemID.BLOODBARK_HELM),
    BLOODBARK_LEGS(ItemID.BLOODBARK_LEGS),
    // Bounty hunter hats
    BOUNTY_HUNTER_HAT_TIER_1(ItemID.BH_HAT_TIER1),
    BOUNTY_HUNTER_HAT_TIER_2(ItemID.BH_HAT_TIER2),
    BOUNTY_HUNTER_HAT_TIER_3(ItemID.BH_HAT_TIER3),
    BOUNTY_HUNTER_HAT_TIER_4(ItemID.BH_HAT_TIER4),
    BOUNTY_HUNTER_HAT_TIER_5(ItemID.BH_HAT_TIER5),
    BOUNTY_HUNTER_HAT_TIER_6(ItemID.BH_HAT_TIER6),
    BRUMA_TORCH(ItemID.WINT_TORCH),
    BRUMA_TORCH_OFFHAND(ItemID.WINT_TORCH_OFFHAND),
    // Carpenter outfit
    CARPENTERS_BOOTS(ItemID.CONSTRUCTION_BOOTS),
    CARPENTERS_HELMET(ItemID.CONSTRUCTION_HAT),
    CARPENTERS_SHIRT(ItemID.CONSTRUCTION_SHIRT),
    CARPENTERS_TROUSERS(ItemID.CONSTRUCTION_TROUSERS),
    // Dagon'hai robes
    DAGONHAI_HAT(ItemID.DAGONHAI_HAT),
    DAGONHAI_ROBE_TOP(ItemID.DAGONHAI_ROBE_TOP),
    DAGONHAI_ROBE_BOTTOM(ItemID.DAGONHAI_ROBE_BOTTOM),
    // Dark flippers
    DARK_FLIPPERS_MAGIC_WARDROBE(ItemID.DARK_FLIPPERS),
    // Dark Squall robes
    DARK_SQUALL_HOOD(ItemID.WGS_DARK_SQUALL_HOOD),
    DARK_SQUALL_ROBE_TOP(ItemID.WGS_DARK_SQUALL_ROBE_TOP),
    DARK_SQUALL_ROBE_BOTTOM(ItemID.WGS_DARK_SQUALL_ROBE_BOTTOM),
    // Elder chaos robes
    ELDER_CHAOS_HOOD(ItemID.ELDERCHAOS_HOOD),
    ELDER_CHAOS_ROBE(ItemID.ELDERCHAOS_BOTTOM),
    ELDER_CHAOS_TOP(ItemID.ELDERCHAOS_TOP),
    // Elder chaos robes (ornate)
    ELDER_CHAOS_TOP_OR(ItemID.ELDERCHAOS_TOP_PRETTY),
    ELDER_CHAOS_ROBE_OR(ItemID.ELDERCHAOS_BOTTOM_PRETTY),
    ELDER_CHAOS_HOOD_OR(ItemID.ELDERCHAOS_HOOD_PRETTY),
    // Evil chicken outfit
    EVIL_CHICKEN_FEET(ItemID.EVIL_CHICKEN_FEET),
    EVIL_CHICKEN_HEAD(ItemID.EVIL_CHICKEN_HEAD),
    EVIL_CHICKEN_LEGS(ItemID.EVIL_CHICKEN_LEGS),
    EVIL_CHICKEN_WINGS(ItemID.EVIL_CHICKEN_WINGS),
    // Fish sack
    FISH_SACK(ItemID.FISH_SACK),
    FISH_SACK_BARREL(ItemID.FISH_SACK_BARREL_CLOSED, true),
    OPEN_FISH_SACK_BARREL(ItemID.FISH_SACK_BARREL_OPEN, true),
    // Trouble Brewing flags, ordered by item id
    CUTTHROAT_FLAG(ItemID.BREW_FLAG_1),
    GILDED_SMILE_FLAG(ItemID.BREW_FLAG_2),
    BRONZE_FIST_FLAG(ItemID.BREW_FLAG_3),
    LUCKY_SHOT_FLAG(ItemID.BREW_FLAG_4),
    TREASURE_FLAG(ItemID.BREW_FLAG_5),
    PHASMATYS_FLAG(ItemID.BREW_FLAG_6),
    // Varlamore Totems
    FLETCHING_KNIFE(ItemID.FLETCHING_KNIFE, true),
    // Forestry Kit, Forestry Basket
    FORESTRY_KIT(ItemID.FORESTRY_KIT, true),
    FORESTRY_BASKET(ItemID.FORESTRY_BASKET_CLOSED, true),
    OPEN_FORESTRY_BASKET(ItemID.FORESTRY_BASKET_OPEN, true),
    // Ghostly robes
    GHOSTLY_BOOTS(ItemID.SECRET_GHOST_BOOTS),
    GHOSTLY_CLOAK(ItemID.SECRET_GHOST_CLOAK),
    GHOSTLY_HOOD(ItemID.SECRET_GHOST_HAT),
    GHOSTLY_ROBE(ItemID.SECRET_GHOST_TOP),
    GHOSTLY_GLOVES(ItemID.SECRET_GHOST_GLOVES),
    GHOSTLY_ROBE_6108(ItemID.SECRET_GHOST_BOTTOM),
    // Golden tench
    GOLDEN_TENCH(ItemID.GOLDEN_TENCH),
    // Graceful
    // Greenman masks
    GREENMAN_MASK(ItemID.GREENMAN_MASK),
    GREENMAN_MASK_NORMAL(ItemID.GREENMAN_MASK_REGULAR),
    GREENMAN_MASK_OAK(ItemID.GREENMAN_MASK_OAK),
    GREENMAN_MASK_WILLOW(ItemID.GREENMAN_MASK_WILLOW),
    GREENMAN_MASK_MAPLE(ItemID.GREENMAN_MASK_MAPLE),
    GREENMAN_MASK_YEW(ItemID.GREENMAN_MASK_YEW),
    GREENMAN_MASK_MAGIC(ItemID.GREENMAN_MASK_MAGIC),
    IMCANDO_HAMMER(ItemID.IMCANDO_HAMMER, true),
    IMCANDO_HAMMER_OFFHAND(ItemID.IMCANDO_HAMMER_OFFHAND, true),
    INFINITY_BOOTS(ItemID.MAGICTRAINING_INFINITYBOOTS),
    INFINITY_BOTTOMS(ItemID.MAGICTRAINING_INFINITYBOTTOM),
    INFINITY_HAT(ItemID.MAGICTRAINING_INFINITYHAT),
    INFINITY_TOP(ItemID.MAGICTRAINING_INFINITYTOP),
    INFINITY_GLOVES(ItemID.MAGICTRAINING_INFINITYGLOVES),
    DARK_INFINITY_BOTTOMS(ItemID.INFINITY_BOTTOM_TRIM),
    DARK_INFINITY_HAT(ItemID.INFINITY_HAT_TRIM),
    DARK_INFINITY_TOP(ItemID.INFINITY_TOP_TRIM),
    LIGHT_INFINITY_BOTTOMS(ItemID.INFINITY_BOTTOM_GOLD),
    LIGHT_INFINITY_HAT(ItemID.INFINITY_HAT_GOLD),
    LIGHT_INFINITY_TOP(ItemID.INFINITY_TOP_GOLD),
    // Log basket
    LOG_BASKET(ItemID.LOG_BASKET_CLOSED, true),
    OPEN_LOG_BASKET(ItemID.LOG_BASKET_OPEN, true),
    // Lunar equipment
    LUNAR_HELM(ItemID.LUNAR_HELMET),
    LUNAR_CAPE(ItemID.LUNAR_CAPE),
    LUNAR_AMULET(ItemID.LUNAR_AMULET),
    LUNAR_BOOTS(ItemID.LUNAR_BOOTS),
    LUNAR_GLOVES(ItemID.LUNAR_GLOVES),
    LUNAR_LEGS(ItemID.LUNAR_LEGS),
    LUNAR_RING(ItemID.LUNAR_RING),
    LUNAR_TORSO(ItemID.LUNAR_TORSO),
    // Tombs of Amascut
    MASK_OF_REBIRTH(ItemID.TOA_AMASCUT_MASK),
    // Moonclan robes
    MOONCLAN_HELM(ItemID.LUNAR_MOONCLAN_HEADGEAR),
    MOONCLAN_CAPE(ItemID.LUNAR_MOONCLAN_CAPE),
    MOONCLAN_BOOTS(ItemID.LUNAR_MOONCLAN_BOOTS),
    MOONCLAN_GLOVES(ItemID.LUNAR_MOONCLAN_GLOVES),
    MOONCLAN_ARMOUR(ItemID.LUNAR_MOONCLAN_TORSO),
    MOONCLAN_SKIRT(ItemID.LUNAR_MOONCLAN_SKIRT),
    // Mudskipper kit
    MUDSKIPPER_HAT(ItemID.MUDSKIPPER_HAT),
    FLIPPERS_MAGIC_WARDROBE(ItemID.MUDSKIPPER_FLIPPERS),
    // Mystic robes
    MYSTIC_BOOTS(ItemID.MYSTIC_BOOTS),
    MYSTIC_HAT(ItemID.MYSTIC_HAT),
    MYSTIC_ROBE_BOTTOM(ItemID.MYSTIC_ROBE_BOTTOM),
    MYSTIC_ROBE_TOP(ItemID.MYSTIC_ROBE_TOP),
    MYSTIC_GLOVES(ItemID.MYSTIC_GLOVES),
    MYSTIC_BOOTS_DARK(ItemID.MYSTIC_BOOTS_DARK),
    MYSTIC_HAT_DARK(ItemID.MYSTIC_HAT_DARK),
    MYSTIC_ROBE_BOTTOM_DARK(ItemID.MYSTIC_ROBE_BOTTOM_DARK),
    MYSTIC_ROBE_TOP_DARK(ItemID.MYSTIC_ROBE_TOP_DARK),
    MYSTIC_GLOVES_DARK(ItemID.MYSTIC_GLOVES_DARK),
    MYSTIC_BOOTS_LIGHT(ItemID.MYSTIC_BOOTS_LIGHT),
    MYSTIC_HAT_LIGHT(ItemID.MYSTIC_HAT_LIGHT),
    MYSTIC_ROBE_BOTTOM_LIGHT(ItemID.MYSTIC_ROBE_BOTTOM_LIGHT),
    MYSTIC_ROBE_TOP_LIGHT(ItemID.MYSTIC_ROBE_TOP_LIGHT),
    MYSTIC_GLOVES_LIGHT(ItemID.MYSTIC_GLOVES_LIGHT),
    MYSTIC_BOOTS_DUSK(ItemID.MYSTIC_BOOTS_DUSK),
    MYSTIC_HAT_DUSK(ItemID.MYSTIC_HAT_DUSK),
    MYSTIC_ROBE_BOTTOM_DUSK(ItemID.MYSTIC_ROBE_BOTTOM_DUSK),
    MYSTIC_ROBE_TOP_DUSK(ItemID.MYSTIC_ROBE_TOP_DUSK),
    MYSTIC_GLOVES_DUSK(ItemID.MYSTIC_GLOVES_DUSK),
    MYSTIC_BOOTS_OR(ItemID.LEAGUE_3_MYSTIC_BOOTS),
    MYSTIC_HAT_OR(ItemID.LEAGUE_3_MYSTIC_HAT),
    MYSTIC_ROBE_BOTTOM_OR(ItemID.LEAGUE_3_MYSTIC_ROBE_BOTTOM),
    MYSTIC_ROBE_TOP_OR(ItemID.LEAGUE_3_MYSTIC_ROBE_TOP),
    MYSTIC_GLOVES_OR(ItemID.LEAGUE_3_MYSTIC_GLOVES),
    // Naval outfits
    BLACK_NAVAL_SHIRT(ItemID.BREW_UNIFORM_BLACK),
    BLACK_NAVY_SLACKS(ItemID.BREW_NAVY_SLACKS_BLACK),
    BLACK_TRICORN_HAT(ItemID.BREW_TRICORN_BLACK),
    BLUE_NAVAL_SHIRT(ItemID.BREW_UNIFORM_BLUE),
    BLUE_NAVY_SLACKS(ItemID.BREW_NAVY_SLACKS_BLUE),
    BLUE_TRICORN_HAT(ItemID.BREW_TRICORN_BLUE),
    BROWN_NAVAL_SHIRT(ItemID.BREW_UNIFORM_BROWN),
    BROWN_NAVY_SLACKS(ItemID.BREW_NAVY_SLACKS_BROWN),
    BROWN_TRICORN_HAT(ItemID.BREW_TRICORN_BROWN),
    GREEN_NAVAL_SHIRT(ItemID.BREW_UNIFORM_GREEN),
    GREEN_NAVY_SLACKS(ItemID.BREW_NAVY_SLACKS_GREEN),
    GREEN_TRICORN_HAT(ItemID.BREW_TRICORN_GREEN),
    GREY_NAVAL_SHIRT(ItemID.BREW_UNIFORM_GREY),
    GREY_NAVY_SLACKS(ItemID.BREW_NAVY_SLACKS_GREY),
    GREY_TRICORN_HAT(ItemID.BREW_TRICORN_GREY),
    PURPLE_NAVAL_SHIRT(ItemID.BREW_UNIFORM_PURPLE),
    PURPLE_NAVY_SLACKS(ItemID.BREW_NAVY_SLACKS_PURPLE),
    PURPLE_TRICORN_HAT(ItemID.BREW_TRICORN_PURPLE),
    RED_NAVAL_SHIRT(ItemID.BREW_UNIFORM_RED),
    RED_NAVY_SLACKS(ItemID.BREW_NAVY_SLACKS_RED),
    RED_TRICORN_HAT(ItemID.BREW_TRICORN_RED),
    // Varlamore orange hat
    ORANGE_31117(ItemID.ORANGE_HAT),
    // Aerial fishing rods
    OILY_PEARL_FISHING_ROD_MAGIC_WARDROBE(ItemID.FISHINGROD_PEARL_OILY),
    PEARL_BARBARIAN_ROD_MAGIC_WARDROBE(ItemID.FISHINGROD_PEARL_BRUT),
    PEARL_FISHING_ROD_MAGIC_WARDROBE(ItemID.FISHINGROD_PEARL),
    PEARL_FLY_FISHING_ROD_MAGIC_WARDROBE(ItemID.FISHINGROD_PEARL_FLY),
    // Pheasant costume
    PHEASANT_CAPE(ItemID.FORESTRY_PHEASANT_CAPE),
    PHEASANT_BOOTS(ItemID.FORESTRY_PHEASANT_BOOTS),
    PHEASANT_HAT(ItemID.FORESTRY_PHEASANT_HAT),
    PHEASANT_LEGS(ItemID.FORESTRY_PHEASANT_LEGS),
    // Pyromancer outfit
    PYROMANCER_BOOTS(ItemID.PYROMANCER_BOOTS),
    PYROMANCER_GARB(ItemID.PYROMANCER_TOP),
    PYROMANCER_HOOD(ItemID.PYROMANCER_HOOD),
    PYROMANCER_ROBE(ItemID.PYROMANCER_BOTTOM),
    // Raiments of the Eye outfits
    HAT_OF_THE_EYE(ItemID.HAT_OF_THE_EYE),
    ROBE_TOP_OF_THE_EYE(ItemID.ROBE_TOP_OF_THE_EYE),
    ROBE_BOTTOMS_OF_THE_EYE(ItemID.ROBE_BOTTOM_OF_THE_EYE),
    BOOTS_OF_THE_EYE(ItemID.BOOTS_OF_THE_EYE),
    HAT_OF_THE_EYE_BLUE(ItemID.HAT_OF_THE_EYE_BLUE),
    ROBE_TOP_OF_THE_EYE_BLUE(ItemID.ROBE_TOP_OF_THE_EYE_BLUE),
    ROBE_BOTTOMS_OF_THE_EYE_BLUE(ItemID.ROBE_BOTTOM_OF_THE_EYE_BLUE),
    HAT_OF_THE_EYE_GREEN(ItemID.HAT_OF_THE_EYE_GREEN),
    ROBE_TOP_OF_THE_EYE_GREEN(ItemID.ROBE_TOP_OF_THE_EYE_GREEN),
    ROBE_BOTTOMS_OF_THE_EYE_GREEN(ItemID.ROBE_BOTTOM_OF_THE_EYE_GREEN),
    HAT_OF_THE_EYE_RED(ItemID.HAT_OF_THE_EYE_RED),
    ROBE_TOP_OF_THE_EYE_RED(ItemID.ROBE_TOP_OF_THE_EYE_RED),
    ROBE_BOTTOMS_OF_THE_EYE_RED(ItemID.ROBE_BOTTOM_OF_THE_EYE_RED),
    // Robes of Ruin
    HOOD_OF_RUIN(ItemID.ROBESOFRUIN_HOOD),
    ROBE_TOP_OF_RUIN(ItemID.ROBESOFRUIN_TOP),
    ROBE_BOTTOM_OF_RUIN(ItemID.ROBESOFRUIN_BOTTOM),
    GLOVES_OF_RUIN(ItemID.ROBESOFRUIN_GLOVES),
    SOCKS_OF_RUIN(ItemID.ROBESOFRUIN_SOCKS),
    CLOAK_OF_RUIN(ItemID.ROBESOFRUIN_CLOAK),
    // Skeletal armour
    SKELETAL_HELM(ItemID.DAGGANOTH_MAGE_HELM),
    SKELETAL_BOTTOMS(ItemID.DAGGANOTH_MAGE_LEGS),
    SKELETAL_BOOTS(ItemID.DAGGANOTH_MAGE_FEET),
    SKELETAL_GLOVES(ItemID.DAGGANOTH_MAGE_GLOVES),
    SKELETAL_TOP(ItemID.DAGGANOTH_MAGE_BODY),
    // Smith's Uniform
    SMITHS_TUNIC(ItemID.SMITHING_UNIFORM_TORSO),
    SMITHS_TROUSERS(ItemID.SMITHING_UNIFORM_LEGS),
    SMITHS_GLOVES(ItemID.SMITHING_UNIFORM_GLOVES),
    SMITHS_GLOVES_I(ItemID.SMITHING_UNIFORM_GLOVES_ICE),
    SMITHS_BOOTS(ItemID.SMITHING_UNIFORM_BOOTS),
    // Splitbark armour
    SPLITBARK_BODY(ItemID.SPLITBARK_BODY),
    SPLITBARK_BOOTS(ItemID.SPLITBARK_GREAVES),
    SPLITBARK_HELM(ItemID.SPLITBARK_HELM),
    SPLITBARK_LEGS(ItemID.SPLITBARK_LEGS),
    SPLITBARK_GAUNTLETS(ItemID.SPLITBARK_GAUNTLETS),
    // Swampbark armour
    SWAMPBARK_BODY(ItemID.SWAMPBARK_BODY),
    SWAMPBARK_BOOTS(ItemID.SWAMPBARK_GREAVES),
    SWAMPBARK_HELM(ItemID.SWAMPBARK_HELM),
    SWAMPBARK_LEGS(ItemID.SWAMPBARK_LEGS),
    SWAMPBARK_GAUNTLETS(ItemID.SWAMPBARK_GAUNTLETS),
    // Tribal outfit (blue)
    TRIBAL_TOP(ItemID.TBW_VILLAGER_SHIRT_CREAM),
    VILLAGER_ROBE(ItemID.TBW_VILLAGER_ROBE_CREAM),
    VILLAGER_HAT(ItemID.TBW_VILLAGER_HAT_CREAM),
    VILLAGER_ARMBAND(ItemID.TBW_VILLAGER_ARMBAND_CREAM),
    VILLAGER_SANDALS(ItemID.TBW_VILLAGER_SANDALS_CREAM),
    // Tribal outfit (brown)
    TRIBAL_TOP_6351(ItemID.TBW_VILLAGER_SHIRT_BLUE),
    VILLAGER_ROBE_6353(ItemID.TBW_VILLAGER_ROBE_BLUE),
    VILLAGER_HAT_6355(ItemID.TBW_VILLAGER_HAT_BLUE),
    VILLAGER_SANDALS_6357(ItemID.TBW_VILLAGER_SANDALS_BLUE),
    VILLAGER_ARMBAND_6359(ItemID.TBW_VILLAGER_ARMBAND_BLUE),
    // Tribal outfit (pink)
    TRIBAL_TOP_6361(ItemID.TBW_VILLAGER_SHIRT_YELLOW),
    VILLAGER_ROBE_6363(ItemID.TBW_VILLAGER_ROBE_YELLOW),
    VILLAGER_HAT_6365(ItemID.TBW_VILLAGER_HAT_YELLOW),
    VILLAGER_SANDALS_6367(ItemID.TBW_VILLAGER_SANDALS_YELLOW),
    VILLAGER_ARMBAND_6369(ItemID.TBW_VILLAGER_ARMBAND_YELLOW),
    // Tribal outfit (yellow)
    TRIBAL_TOP_6371(ItemID.TBW_VILLAGER_SHIRT_PURPLE),
    VILLAGER_ROBE_6373(ItemID.TBW_VILLAGER_ROBE_PURPLE),
    VILLAGER_HAT_6375(ItemID.TBW_VILLAGER_HAT_PURPLE),
    VILLAGER_SANDALS_6377(ItemID.TBW_VILLAGER_SANDALS_PURPLE),
    VILLAGER_ARMBAND_6379(ItemID.TBW_VILLAGER_ARMBAND_PURPLE),
    // Twilight Emissary Robes
    EMISSARY_HOOD(ItemID.VMQ3_CULTIST_HOOD),
    EMISSARY_ROBE_TOP(ItemID.VMQ3_CULTIST_ROBE_TOP),
    EMISSARY_ROBE_BOTTOM(ItemID.VMQ3_CULTIST_ROBE_BOTTOM),
    EMISSARY_SANDALS(ItemID.VMQ3_CULTIST_SANDALS),
    // Virtus robes
    VIRTUS_MASK(ItemID.VIRTUS_MASK, true),
    VIRTUS_ROBE_BOTTOM(ItemID.VIRTUS_LEGS, true),
    VIRTUS_ROBE_TOP(ItemID.VIRTUS_TOP, true),
    // Virtus robes (Echo)
    ECHO_VIRTUS_MASK(ItemID.VIRTUS_MASK_ORNAMENT, true),
    ECHO_VIRTUS_ROBE_TOP(ItemID.VIRTUS_TOP_ORNAMENT, true),
    ECHO_VIRTUS_ROBE_BOTTOM(ItemID.VIRTUS_LEGS_ORNAMENT, true),
    // Warm gloves
    WARM_GLOVES(ItemID.PYROMANCER_GLOVES),
    // Zealot's robes
    ZEALOTS_BOOTS(ItemID.SHADES_PRAYER_BOOTS),
    ZEALOTS_HELM(ItemID.SHADES_PRAYER_HELM),
    ZEALOTS_ROBE_BOTTOM(ItemID.SHADES_PRAYER_BOTTOM),
    ZEALOTS_ROBE_TOP(ItemID.SHADES_PRAYER_TOP);


    private final int itemID;
    @Getter
    private final String location = "Magic Wardrobe";
    @Getter
    private final boolean isBis;

    MagicWardrobe(int itemID, boolean isBis) {
        this.itemID = itemID; this.isBis = isBis;
    }
    MagicWardrobe(int itemID) {
        this.itemID = itemID;
        this.isBis = false;
    }
}
