/*
 * BSD 2-Clause License
 *
 * Copyright (c) 2021, Riley McGee
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package com.wastedbankspace.model.locations;

import com.wastedbankspace.model.StorableItem;
import lombok.Getter;
import net.runelite.api.Item;
import net.runelite.api.gameval.ItemID;

@Getter
public enum PetHouse implements StorableItem {
    //PVM and Minigame Pets
    PET_CHAOS_ELEMENTAL(ItemID.CHAOSELEPET),
    PET_DAGANNOTH_SUPREME(ItemID.SUPREMEPET),
    PET_DAGANNOTH_PRIME(ItemID.PRIMEPET),
    PET_DAGANNOTH_REX(ItemID.REXPET),
    PET_PENANCE_QUEEN(ItemID.PENANCEPET),
    PET_KREEARRA(ItemID.ARMADYLPET),
    PET_GENERAL_GRAARDOR(ItemID.BANDOSPET),
    PET_ZILYANA(ItemID.SARADOMINPET),
    PET_KRIL_TSUTAROTH(ItemID.ZAMORAKPET),
    PET_BABY_MOLE(ItemID.MOLEPET),
    PET_PRINCE_BLACK_DRAGON(ItemID.KBDPET),
    PET_KALPHITE_PRINCESS(ItemID.KQPET_WALKING),
    KALPHITE_PRINCESS_12654(ItemID.KQPET_FLYING), //KQ Transmog FLying
    PET_SMOKE_DEVIL(ItemID.SMOKEPET),
    PET_KRAKEN(ItemID.KRAKENPET),
    PET_DARK_CORE(ItemID.COREPET),
    CORPOREAL_CRITTER(ItemID.CORPPET),
    PET_SNAKELING(ItemID.SNAKEPET),
    PET_SNAKELING_12939(ItemID.SNAKEPET_ORANGE),
    PET_SNAKELING_12940(ItemID.SNAKEPET_BLUE),
    CHOMPY_CHICK(ItemID.CHOMPYBIRD_PET),
    VENENATIS_SPIDERLING(ItemID.VENENATIS_PET),
    VENENATIS_SPIDERLING_27648(ItemID.VENENATIS_PET_LEGACY),
    CALLISTO_CUB(ItemID.CALLISTO_PET),
    CALLISTO_CUB_27649(ItemID.CALLISTO_PET_LEGACY),
    VETION_JR(ItemID.VETION_PET),
    VETION_JR_13180(ItemID.VETION_PET2),
    VETION_JR_27650(ItemID.VETION_PET_LEGACY),
    VETION_JR_27651(ItemID.VETION_PET2_LEGACY),
    SCORPIAS_OFFSPRING(ItemID.SCORPIA_PET),
    TZREKJAD(ItemID.JAD_PET),
    JALREKJA(ItemID.JAD_PET_INFERNO),
    HELLPUPPY(ItemID.HELL_PET),
    ABYSSAL_ORPHAN(ItemID.ABYSSALSIRE_PET),
    OLMLET(ItemID.OLMPET),
    PUPPADILE(ItemID.DOGADILEPET),
    TEKTINY(ItemID.TEKTONPET),
    ENRAGED_TEKTINY(ItemID.TEKTONENRAGEDPET),
    VANGUARD(ItemID.VANGUARDPET),
    VASA_MINIRIO(ItemID.VASAPET),
    VESPINA(ItemID.VESPULAPET),
    FLYING_VESPINA(ItemID.VESPULAFLYINGPET),
    SKOTOS(ItemID.SKOTIZOPET),
    JALNIBREK(ItemID.INFERNOPET),
    TZREKZUK(ItemID.INFERNOPET_ZUK),
    HERBI(ItemID.HERBIBOARPET),
    NOON(ItemID.DAWNPET),
    VORKI(ItemID.VORKATHPET),
    LIL_ZIK(ItemID.VERZIKPET),
    LIL_MAIDEN(ItemID.MAIDENPET),
    LIL_BLOAT(ItemID.BLOATPET),
    LIL_NYLO(ItemID.NYLOCASPET),
    LIL_SOT(ItemID.SOTETSEGPET),
    LIL_XARP(ItemID.XARPUSPET),
    IKKLE_HYDRA(ItemID.HYDRAPET),
    IKKLE_HYDRA_22748(ItemID.HYDRAPET_ELECTRIC),
    IKKLE_HYDRA_22750(ItemID.HYDRAPET_FIRE),
    IKKLE_HYDRA_22752(ItemID.HYDRAPET_EXTINGUISHED),
    SRARACHA(ItemID.SARACHNISPET),
    SRARACHA_25842(ItemID.SARACHNISPET_ORANGE),
    SRARACHA_25843(ItemID.SARACHNISPET_BLUE),
    YOUNGLLEF(ItemID.GAUNTLETPET),
    CORRUPTED_YOUNGLLEF(ItemID.GAUNTLETPET_CORRUPT),
    SMOLCANO(ItemID.ZALCANOPET),
    LITTLE_NIGHTMARE(ItemID.NIGHTMAREPET),
    LITTLE_PARASITE(ItemID.NIGHTMAREPET_PARASITE),
    LIL_CREATOR(ItemID.SOULWARSPET_BLUE),
    LIL_DESTRUCTOR(ItemID.SOULWARSPET_RED),
    TINY_TEMPOR(ItemID.TEMPOROSSPET),
    NEXLING(ItemID.NEXPET),
    ABYSSAL_PROTECTOR(ItemID.ABYSSALPET),
    TUMEKENS_GUARDIAN(ItemID.WARDENPET_TUMEKEN),
    TUMEKENS_DAMAGED_GUARDIAN(ItemID.WARDENPET_TUMEKEN_DESTROYED),
    ELIDINIS_GUARDIAN(ItemID.WARDENPET_ELIDINIS),
    ELIDINIS_DAMAGED_GUARDIAN(ItemID.WARDENPET_ELIDINIS_DESTROYED),
    AKKHITO(ItemID.WARDENPET_AKKHA),
    BABI(ItemID.WARDENPET_BABA),
    KEPHRITI(ItemID.WARDENPET_KEPHRI),
    ZEBO(ItemID.WARDENPET_ZEBAK),
    MUPHIN(ItemID.MUSPAHPET),
    WISP(ItemID.WHISPERERPET),
    BUTCH(ItemID.VARDORVISPET),
    LILVIATHAN(ItemID.LEVIATHANPET),
    BARON(ItemID.DUKESUCELLUSPET),
    SCURRY(ItemID.SCURRIUSPET),
    SMOL_HEREDIT(ItemID.SOLHEREDITPET),
    QUETZIN(ItemID.QUETZALPET),
    NID(ItemID.ARAXXORPET),
    RAX(ItemID.ARAXXORPET_CUTE),    //NID Transmog
    HUBERTE(ItemID.HUEYPET),
    MOXI(ItemID.AMOXLIATLPET),
    BRAN(ItemID.RTBRANDAPET),
    RIC(ItemID.RTELDRICPET),    //BRAN Transmog
    YAMI(ItemID.YAMAPET),
    DOM(ItemID.DOMPET),

    //Skilling Pets
    HERON(ItemID.SKILLPETFISH),
    GREAT_BLUE_HERON(ItemID.SKILLPETFISH_TEMPOROSS),
    ROCK_GOLEM(ItemID.SKILLPETMINING),
    ROCK_GOLEM_21188(ItemID.SKILLPETMINING_COPPER),
    ROCK_GOLEM_21189(ItemID.SKILLPETMINING_IRON),
    ROCK_GOLEM_21190(ItemID.SKILLPETMINING_BLURITE),
    ROCK_GOLEM_21187(ItemID.SKILLPETMINING_TIN),
    ROCK_GOLEM_21191(ItemID.SKILLPETMINING_SILVER),
    ROCK_GOLEM_21192(ItemID.SKILLPETMINING_COAL),
    ROCK_GOLEM_21193(ItemID.SKILLPETMINING_GOLD),
    ROCK_GOLEM_21194(ItemID.SKILLPETMINING_MITHRIL),
    ROCK_GOLEM_21195(ItemID.SKILLPETMINING_GRANITE),
    ROCK_GOLEM_21196(ItemID.SKILLPETMINING_ADAMANTITE),
    ROCK_GOLEM_21197(ItemID.SKILLPETMINING_RUNITE),
    ROCK_GOLEM_21340(ItemID.SKILLPETMINING_AMETHYST),
    ROCK_GOLEM_21358(ItemID.SKILLPETMINING_LOVAKITE),
    ROCK_GOLEM_21359(ItemID.SKILLPETMINING_ELEMENTAL),
    ROCK_GOLEM_21360(ItemID.SKILLPETMINING_DAEYALT),
    BEAVER(ItemID.SKILLPETWC),
    BEAVER_28229(ItemID.SKILLPET_WC_OAK),
    BEAVER_28230(ItemID.SKILLPET_WC_WILLOW),
    BEAVER_28231(ItemID.SKILLPET_WC_MAPLE),
    BEAVER_28232(ItemID.SKILLPET_WC_YEW),
    BEAVER_28233(ItemID.SKILLPET_WC_MAGIC),
    BEAVER_28234(ItemID.SKILLPET_WC_REDWOOD),
    BEAVER_28235(ItemID.SKILLPET_WC_TEAK),
    BEAVER_28236(ItemID.SKILLPET_WC_MAHOGANY),
    BEAVER_28237(ItemID.SKILLPET_WC_ARCTIC),
    FOX_28670(ItemID.SKILLPET_WC_FOX),
    PHEASANT(ItemID.SKILLPET_WC_PHEASANT),
    BABY_CHINCHOMPA(ItemID.SKILLPETHUNTER_RED),
    BABY_CHINCHOMPA_13324(ItemID.SKILLPETHUNTER_GREY),
    BABY_CHINCHOMPA_13325(ItemID.SKILLPETHUNTER_BLACK),
    BABY_CHINCHOMPA_13326(ItemID.SKILLPETHUNTER_GOLD),
    BLOODHOUND(ItemID.BLOODHOUND_PET),
    GIANT_SQUIRREL(ItemID.SKILLPETAGILITY),
    DARK_SQUIRREL(ItemID.SKILLPETAGILITY_DARK),
    BONE_SQUIRREL(ItemID.SKILLPETAGILITY_BONE),
    TANGLEROOT(ItemID.SKILLPETFARMING),
    TANGLEROOT_24555(ItemID.SKILLPETFARMING_CRYSTAL),
    TANGLEROOT_24557(ItemID.SKILLPETFARMING_DRAGON),
    TANGLEROOT_24559(ItemID.SKILLPETFARMING_HERB),
    TANGLEROOT_24561(ItemID.SKILLPETFARMING_LILY),
    TANGLEROOT_24563(ItemID.SKILLPETFARMING_REDWOOD),
    RIFT_GUARDIAN(ItemID.SKILLPETRUNECRAFTING_FIRE),
    RIFT_GUARDIAN_20667(ItemID.SKILLPETRUNECRAFTING_AIR),
    RIFT_GUARDIAN_20669(ItemID.SKILLPETRUNECRAFTING_MIND),
    RIFT_GUARDIAN_20671(ItemID.SKILLPETRUNECRAFTING_WATER),
    RIFT_GUARDIAN_20673(ItemID.SKILLPETRUNECRAFTING_EARTH),
    RIFT_GUARDIAN_20675(ItemID.SKILLPETRUNECRAFTING_BODY),
    RIFT_GUARDIAN_20677(ItemID.SKILLPETRUNECRAFTING_COSMIC),
    RIFT_GUARDIAN_20679(ItemID.SKILLPETRUNECRAFTING_CHAOS),
    RIFT_GUARDIAN_20681(ItemID.SKILLPETRUNECRAFTING_NATURE),
    RIFT_GUARDIAN_20683(ItemID.SKILLPETRUNECRAFTING_LAW),
    RIFT_GUARDIAN_20685(ItemID.SKILLPETRUNECRAFTING_DEATH),
    RIFT_GUARDIAN_20687(ItemID.SKILLPETRUNECRAFTING_SOUL),
    RIFT_GUARDIAN_20689(ItemID.SKILLPETRUNECRAFTING_ASTRAL),
    RIFT_GUARDIAN_21990(ItemID.SKILLPETRUNECRAFTING_WRATH),
    RIFT_GUARDIAN_20691(ItemID.SKILLPETRUNECRAFTING_BLOOD),
    GREATISH_GUARDIAN(ItemID.SKILLPETRUNECRAFTING_GOTR),
    ROCKY(ItemID.SKILLPETTHIEVING),
    RED(ItemID.SKILLPETTHIEVING_PANDA),
    ZIGGY(ItemID.SKILLPETTHIEVING_TANUKI),
    PHOENIX(ItemID.PHOENIXPET),
    PHOENIX_24483(ItemID.PHOENIXPET_GREEN),
    PHOENIX_24484(ItemID.PHOENIXPET_BLUE),
    PHOENIX_24485(ItemID.PHOENIXPET_WHITE),
    PHOENIX_24486(ItemID.PHOENIXPET_PURPLE),

    // Extras
    PET_KITTEN(ItemID.KITTENOBJECT),
    PET_KITTEN_1556(ItemID.KITTENOBJECT_LIGHT),
    PET_KITTEN_1557(ItemID.KITTENOBJECT_BROWN),
    PET_KITTEN_1558(ItemID.KITTENOBJECT_BLACK),
    PET_KITTEN_1559(ItemID.KITTENOBJECT_BROWNGREY),
    PET_KITTEN_1560(ItemID.KITTENOBJECT_BLUEGREY),
    PET_CAT(ItemID.GROWNCATOBJECT),
    PET_CAT_1562(ItemID.GROWNCATOBJECT_LIGHT),
    PET_CAT_1563(ItemID.GROWNCATOBJECT_BROWN),
    PET_CAT_1564(ItemID.GROWNCATOBJECT_BLACK),
    PET_CAT_1565(ItemID.GROWNCATOBJECT_BROWNGREY),
    PET_CAT_1566(ItemID.GROWNCATOBJECT_BLUEGREY),
    PET_CAT_1567(ItemID.OVERGROWNCATOBJECT), // overgrown
    PET_CAT_1568(ItemID.OVERGROWNCATOBJECT_LIGHT), // overgrown
    PET_CAT_1569(ItemID.OVERGROWNCATOBJECT_BROWN), // overgrown
    PET_CAT_1570(ItemID.OVERGROWNCATOBJECT_BLACK), // overgrown
    PET_CAT_1571(ItemID.OVERGROWNCATOBJECT_BROWNGREY), // overgrown
    PET_CAT_1572(ItemID.OVERGROWNCATOBJECT_BLUEGREY), // overgrown
    WILY_CAT(ItemID.WILEYCATOBJECT_LIGHT),
    WILY_CAT_6556(ItemID.WILEYCATOBJECT),
    WILY_CAT_6557(ItemID.WILEYCATOBJECT_BROWN),
    WILY_CAT_6558(ItemID.WILEYCATOBJECT_BLACK),
    WILY_CAT_6559(ItemID.WILEYCATOBJECT_BROWNGREY),
    WILY_CAT_6560(ItemID.WILEYCATOBJECT_BLUEGREY),
    LAZY_CAT(ItemID.LAZYCATOBJECT_LIGHT),
    LAZY_CAT_6550(ItemID.LAZYCATOBJECT),
    LAZY_CAT_6551(ItemID.LAZYCATOBJECT_BROWN),
    LAZY_CAT_6552(ItemID.LAZYCATOBJECT_BLACK),
    LAZY_CAT_6553(ItemID.LAZYCATOBJECT_BROWNGREY),
    LAZY_CAT_6554(ItemID.LAZYCATOBJECT_BLUEGREY),
    HELLKITTEN(ItemID.KITTENOBJECT_HELL),
    HELL_CAT(ItemID.GROWNCATOBJECT_HELL),
    OVERGROWN_HELLCAT(ItemID.OVERGROWNCATOBJECT_HELL),
    WILY_HELLCAT(ItemID.WILEYCATOBJECT_HELL),
    LAZY_HELL_CAT(ItemID.LAZYCATOBJECT_HELL),
    TOY_CAT(ItemID.POH_TOY_CAT),
    FISHBOWL_6670(ItemID.FISHBOWL_BLUEFISH),
    FISHBOWL_6671(ItemID.FISHBOWL_GREENFISH),
    FISHBOWL_6672(ItemID.FISHBOWL_SPINEFISH),
    PET_ROCK(ItemID.VT_USELESS_ROCK),
    EGG_30970(ItemID.SCRAMBLED_EGG), //Humphry Dumphry
    BROAV(ItemID.WGS_BROAV);

    private final int itemID;
    @Getter
    private final String location = "Pet House";
    @Getter
    private final boolean isBis;
    PetHouse(int itemID) {
        this.itemID = itemID;
        this.isBis = false;
    }
}
