/*
 * BSD 2-Clause License
 *
 * Copyright (c) 2021, Riley McGee
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package com.wastedbankspace.model.locations;

import com.wastedbankspace.model.StorableItem;
import lombok.Getter;
import net.runelite.api.gameval.ItemID;

@Getter
public enum TackleBox implements StorableItem {
    //Equipment
    ANGLER_BOOTS(ItemID.TRAWLER_REWARD_BOOTS),
    ANGLER_HAT(ItemID.TRAWLER_REWARD_HAT),
    ANGLER_TOP(ItemID.TRAWLER_REWARD_TOP),
    ANGLER_WADERS(ItemID.TRAWLER_REWARD_LEGS),

    SPIRIT_ANGLER_BOOTS(ItemID.SPIRIT_ANGLER_BOOTS),
    SPIRIT_ANGLER_HEADBAND(ItemID.SPIRIT_ANGLER_HAT),
    SPIRIT_ANGLER_TOP(ItemID.SPIRIT_ANGLER_TOP),
    SPIRIT_ANGLER_WADERS(ItemID.SPIRIT_ANGLER_LEGS),

    FISHBOWL_HELMET(ItemID.HUNDRED_PIRATE_DIVING_HELMET),
    FLIPPERS(ItemID.MUDSKIPPER_FLIPPERS),
    DARK_FLIPPERS(ItemID.DARK_FLIPPERS),
    DIVING_APPARATUS(ItemID.HUNDRED_PIRATE_DIVING_BACKPACK),

    RADAS_BLESSING_1(ItemID.ZEAH_BLESSING_EASY),
    RADAS_BLESSING_2(ItemID.ZEAH_BLESSING_MEDIUM),
    RADAS_BLESSING_3(ItemID.ZEAH_BLESSING_HARD),
    RADAS_BLESSING_4(ItemID.ZEAH_BLESSING_ELITE),

    TINY_NET(ItemID.TINY_NET),
    HARPOON(ItemID.HARPOON),
    BARBTAIL_HARPOON(ItemID.HUNTING_BARBED_HARPOON),
    DRAGON_HARPOON(ItemID.DRAGON_HARPOON),
    INFERNAL_HARPOON(ItemID.INFERNAL_HARPOON),
    DRAGON_HARPOON_OR(ItemID.TRAILBLAZER_HARPOON_NO_INFERNAL),
    INFERNAL_HARPOON_OR(ItemID.TRAILBLAZER_HARPOON),
    CRYSTAL_HARPOON(ItemID.CRYSTAL_HARPOON),
    MERFOLK_TRIDENT(ItemID.MERFOLK_TRIDENT),
    FISHING_ROD(ItemID.FISHING_ROD),
    FLY_FISHING_ROD(ItemID.FLY_FISHING_ROD),
    OILY_FISHING_ROD(ItemID.OILY_FISHING_ROD),
    BARBARIAN_ROD(ItemID.BRUT_FISHING_ROD),
    PEARL_FISHING_ROD(ItemID.FISHINGROD_PEARL),
    PEARL_FLY_FISHING_ROD(ItemID.FISHINGROD_PEARL_FLY),
    OILY_PEARL_FISHING_ROD(ItemID.FISHINGROD_PEARL_OILY),
    PEARL_BARBARIAN_ROD(ItemID.FISHINGROD_PEARL_BRUT),
    SMALL_FISHING_NET(ItemID.NET),
    BIG_FISHING_NET(ItemID.BIG_NET),
    DRIFT_NET(ItemID.FOSSIL_DRIFT_NET),
    LOBSTER_POT(ItemID.LOBSTER_POT),
    KARAMBWAN_VESSEL(ItemID.TBWT_KARAMBWAN_VESSEL),
    KARAMBWAN_VESSEL_FILLED(ItemID.TBWT_KARAMBWAN_VESSEL_LOADED_WITH_KARAMBWANJI),

    //Bait
    SPIRIT_FLAKES(ItemID.SPIRIT_FLAKES),
    FEATHERS(ItemID.FEATHER),
    RAW_KARAMBWANJI(ItemID.TBWT_RAW_KARAMBWANJI),
    FISHING_BAIT(ItemID.FISHING_BAIT),
    DARK_FISHING_BAIT(ItemID.WILDERNESS_FISHING_BAIT),
    SANDWORMS(ItemID.PISCARILIUS_SANDWORMS),
    FISH_OFFCUTS(ItemID.BRUT_FISH_CUTS),
    FISH_CHUNKS(ItemID.FISH_CHUNKS),
    //Misc
    FISHING_POTION1(ItemID._1DOSEFISHERSPOTION),
    FISHING_POTION2(ItemID._2DOSEFISHERSPOTION),
    FISHING_POTION3(ItemID._3DOSEFISHERSPOTION),
    FISHING_POTION4(ItemID._4DOSEFISHERSPOTION),
    MOLCH_PEARLS(ItemID.AERIAL_FISHING_PEARL);

    private final int itemID;
    @Getter
    private final String location = "Tackle Box";
    @Getter
    private final boolean isBis;
    TackleBox(int itemID) {
        this.itemID = itemID;
        this.isBis = false;
    }
}
